//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 10:01:03 AM CEST 
//


package nl.b3p.stri._2008._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.b3p.stri._2008._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.b3p.stri._2008._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Plan.Eigenschappen }
     * 
     */
    public Plan.Eigenschappen createPlanEigenschappen() {
        return new Plan.Eigenschappen();
    }

    /**
     * Create an instance of {@link Plan.Onderdelen }
     * 
     */
    public Plan.Onderdelen createPlanOnderdelen() {
        return new Plan.Onderdelen();
    }

    /**
     * Create an instance of {@link Plan.Supplementen }
     * 
     */
    public Plan.Supplementen createPlanSupplementen() {
        return new Plan.Supplementen();
    }

    /**
     * Create an instance of {@link GeleideFormulier }
     * 
     */
    public GeleideFormulier createGeleideFormulier() {
        return new GeleideFormulier();
    }

}
