//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.29 at 03:18:07 PM CEST 
//


package nl.b3p.imro._2008._11;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctieaanduidingenEnumerationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FunctieaanduidingenEnumerationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="aanlegsteiger"/>
 *     &lt;enumeration value="agrarisch"/>
 *     &lt;enumeration value="agrarisch bedrijf"/>
 *     &lt;enumeration value="agrarisch loonbedrijf"/>
 *     &lt;enumeration value="agrarisch met waarden"/>
 *     &lt;enumeration value="akkerbouw"/>
 *     &lt;enumeration value="ambachtelijke be- en verwerking agrarische producten"/>
 *     &lt;enumeration value="aquacultuur"/>
 *     &lt;enumeration value="aquaduct"/>
 *     &lt;enumeration value="archeologische waarden"/>
 *     &lt;enumeration value="asielzoekerscentrum"/>
 *     &lt;enumeration value="atelier"/>
 *     &lt;enumeration value="attractiepark"/>
 *     &lt;enumeration value="autocircuit"/>
 *     &lt;enumeration value="baggerspeciedepot"/>
 *     &lt;enumeration value="bed &amp; breakfast"/>
 *     &lt;enumeration value="bedrijf"/>
 *     &lt;enumeration value="bedrijf aan huis"/>
 *     &lt;enumeration value="bedrijfswoning"/>
 *     &lt;enumeration value="bedrijventerrein"/>
 *     &lt;enumeration value="beeldbepalende boom"/>
 *     &lt;enumeration value="begraafplaats"/>
 *     &lt;enumeration value="belwinkel"/>
 *     &lt;enumeration value="beroep aan huis"/>
 *     &lt;enumeration value="bibliotheek"/>
 *     &lt;enumeration value="bioscoop"/>
 *     &lt;enumeration value="bollenteelt"/>
 *     &lt;enumeration value="bomenteelt"/>
 *     &lt;enumeration value="bordeel"/>
 *     &lt;enumeration value="bos"/>
 *     &lt;enumeration value="bowlingbaan"/>
 *     &lt;enumeration value="brandweerkazerne"/>
 *     &lt;enumeration value="brug"/>
 *     &lt;enumeration value="caravanstalling"/>
 *     &lt;enumeration value="casino"/>
 *     &lt;enumeration value="centrum"/>
 *     &lt;enumeration value="congrescentrum"/>
 *     &lt;enumeration value="creativiteitscentrum"/>
 *     &lt;enumeration value="crematorium"/>
 *     &lt;enumeration value="cultuur en ontspanning"/>
 *     &lt;enumeration value="cultuurhistorische waarden"/>
 *     &lt;enumeration value="dagrecreatie"/>
 *     &lt;enumeration value="dansschool"/>
 *     &lt;enumeration value="detailhandel"/>
 *     &lt;enumeration value="detailhandel grootschalig"/>
 *     &lt;enumeration value="detailhandel in brand en explosiegevaarlijke goederen"/>
 *     &lt;enumeration value="detailhandel perifeer"/>
 *     &lt;enumeration value="detailhandel volumineus"/>
 *     &lt;enumeration value="dienstverlening"/>
 *     &lt;enumeration value="dierenasiel"/>
 *     &lt;enumeration value="dierentuin"/>
 *     &lt;enumeration value="discotheek"/>
 *     &lt;enumeration value="drafbaan"/>
 *     &lt;enumeration value="drugsopvang"/>
 *     &lt;enumeration value="ecologische verbindingszone"/>
 *     &lt;enumeration value="ecologische waarde"/>
 *     &lt;enumeration value="eendenkooi"/>
 *     &lt;enumeration value="erf"/>
 *     &lt;enumeration value="evenemententerrein"/>
 *     &lt;enumeration value="feestzaal"/>
 *     &lt;enumeration value="fruitteelt"/>
 *     &lt;enumeration value="garage"/>
 *     &lt;enumeration value="geluidscherm"/>
 *     &lt;enumeration value="geluidwal"/>
 *     &lt;enumeration value="gemaal"/>
 *     &lt;enumeration value="gemengd"/>
 *     &lt;enumeration value="geomorfologische waarde"/>
 *     &lt;enumeration value="gezondheidszorg"/>
 *     &lt;enumeration value="glastuinbouw"/>
 *     &lt;enumeration value="golfbaan"/>
 *     &lt;enumeration value="groen"/>
 *     &lt;enumeration value="gronddepot"/>
 *     &lt;enumeration value="grondgebonden veehouderij"/>
 *     &lt;enumeration value="groothandel"/>
 *     &lt;enumeration value="haven"/>
 *     &lt;enumeration value="horeca"/>
 *     &lt;enumeration value="houtsingel"/>
 *     &lt;enumeration value="houtwal"/>
 *     &lt;enumeration value="hovenier"/>
 *     &lt;enumeration value="ijsbaan"/>
 *     &lt;enumeration value="infrastructuur"/>
 *     &lt;enumeration value="intensieve kwekerij"/>
 *     &lt;enumeration value="intensieve veehouderij"/>
 *     &lt;enumeration value="internetcafé"/>
 *     &lt;enumeration value="internetwinkel"/>
 *     &lt;enumeration value="jachthaven"/>
 *     &lt;enumeration value="jeugdopvang"/>
 *     &lt;enumeration value="jongeren ontmoetingsplek"/>
 *     &lt;enumeration value="justitiële inrichting"/>
 *     &lt;enumeration value="kamerverhuur"/>
 *     &lt;enumeration value="kampeerboerderij"/>
 *     &lt;enumeration value="kampeerterrein"/>
 *     &lt;enumeration value="kantoor"/>
 *     &lt;enumeration value="kartbaan"/>
 *     &lt;enumeration value="kas"/>
 *     &lt;enumeration value="kazerne"/>
 *     &lt;enumeration value="kinderboerderij"/>
 *     &lt;enumeration value="kunstijsbaan"/>
 *     &lt;enumeration value="laad- en losplaats"/>
 *     &lt;enumeration value="landingsbaan"/>
 *     &lt;enumeration value="landschapswaarden"/>
 *     &lt;enumeration value="leidingstrook"/>
 *     &lt;enumeration value="ligplaats"/>
 *     &lt;enumeration value="luchthaven"/>
 *     &lt;enumeration value="luchtverkeer"/>
 *     &lt;enumeration value="maatschappelijk"/>
 *     &lt;enumeration value="manege"/>
 *     &lt;enumeration value="markt"/>
 *     &lt;enumeration value="meer"/>
 *     &lt;enumeration value="militaire zaken"/>
 *     &lt;enumeration value="militair oefenterrein"/>
 *     &lt;enumeration value="modelvliegtuigbaan"/>
 *     &lt;enumeration value="monumentale boom"/>
 *     &lt;enumeration value="motorcrossterrein"/>
 *     &lt;enumeration value="munitiedepot"/>
 *     &lt;enumeration value="museum"/>
 *     &lt;enumeration value="muziekschool"/>
 *     &lt;enumeration value="muziektheater"/>
 *     &lt;enumeration value="naschoolse opvang"/>
 *     &lt;enumeration value="natuur- en landschapswaarden"/>
 *     &lt;enumeration value="natuur"/>
 *     &lt;enumeration value="natuurwaarden"/>
 *     &lt;enumeration value="nutsbedrijf"/>
 *     &lt;enumeration value="nutsvoorziening"/>
 *     &lt;enumeration value="oever"/>
 *     &lt;enumeration value="onderwijs"/>
 *     &lt;enumeration value="ontsluiting"/>
 *     &lt;enumeration value="openbaar vervoer"/>
 *     &lt;enumeration value="openbare dienstverlening"/>
 *     &lt;enumeration value="opslag"/>
 *     &lt;enumeration value="openbaar vervoerstation"/>
 *     &lt;enumeration value="paardenfokkerij"/>
 *     &lt;enumeration value="paardenhouderij"/>
 *     &lt;enumeration value="pad"/>
 *     &lt;enumeration value="park"/>
 *     &lt;enumeration value="parkeergarage"/>
 *     &lt;enumeration value="parkeerterrein"/>
 *     &lt;enumeration value="partyboerderij"/>
 *     &lt;enumeration value="passantenhaven"/>
 *     &lt;enumeration value="pitch &amp; putt"/>
 *     &lt;enumeration value="plantsoen"/>
 *     &lt;enumeration value="plein"/>
 *     &lt;enumeration value="praktijkruimte"/>
 *     &lt;enumeration value="prostitutie"/>
 *     &lt;enumeration value="raamprostitutie (raamexploitatie)"/>
 *     &lt;enumeration value="railverkeer"/>
 *     &lt;enumeration value="recreatie"/>
 *     &lt;enumeration value="recreatiewoning"/>
 *     &lt;enumeration value="religie"/>
 *     &lt;enumeration value="risicovolle inrichting"/>
 *     &lt;enumeration value="rivier"/>
 *     &lt;enumeration value="sauna"/>
 *     &lt;enumeration value="schiphuis"/>
 *     &lt;enumeration value="seksinrichting"/>
 *     &lt;enumeration value="sierteelt"/>
 *     &lt;enumeration value="silo"/>
 *     &lt;enumeration value="skeelerbaan"/>
 *     &lt;enumeration value="skibaan"/>
 *     &lt;enumeration value="sluis"/>
 *     &lt;enumeration value="speeltuin"/>
 *     &lt;enumeration value="speelvoorziening"/>
 *     &lt;enumeration value="spoorweg"/>
 *     &lt;enumeration value="sport"/>
 *     &lt;enumeration value="sportcentrum"/>
 *     &lt;enumeration value="sporthal"/>
 *     &lt;enumeration value="sportveld"/>
 *     &lt;enumeration value="sportzaal"/>
 *     &lt;enumeration value="squashcentrum"/>
 *     &lt;enumeration value="stadion"/>
 *     &lt;enumeration value="steiger"/>
 *     &lt;enumeration value="strand"/>
 *     &lt;enumeration value="strandhuis"/>
 *     &lt;enumeration value="studentenhuisvesting"/>
 *     &lt;enumeration value="stuw"/>
 *     &lt;enumeration value="supermarkt"/>
 *     &lt;enumeration value="tennisbaan"/>
 *     &lt;enumeration value="terras"/>
 *     &lt;enumeration value="theater"/>
 *     &lt;enumeration value="tuin"/>
 *     &lt;enumeration value="tuinbouw"/>
 *     &lt;enumeration value="tuincentrum"/>
 *     &lt;enumeration value="tunnel"/>
 *     &lt;enumeration value="uitvaartcentrum"/>
 *     &lt;enumeration value="vaarweg"/>
 *     &lt;enumeration value="veerhaven"/>
 *     &lt;enumeration value="ven"/>
 *     &lt;enumeration value="verblijfsgebied"/>
 *     &lt;enumeration value="verblijfsrecreatie"/>
 *     &lt;enumeration value="verenigingsleven"/>
 *     &lt;enumeration value="verkeer"/>
 *     &lt;enumeration value="verkoop eigen producten"/>
 *     &lt;enumeration value="verkooppunt motorbrandstoffen met lpg"/>
 *     &lt;enumeration value="verkooppunt motorbrandstoffen zonder lpg"/>
 *     &lt;enumeration value="vertrek- en aankomsthal"/>
 *     &lt;enumeration value="vijver"/>
 *     &lt;enumeration value="viskwekerij"/>
 *     &lt;enumeration value="volkstuin"/>
 *     &lt;enumeration value="vulpunt lpg"/>
 *     &lt;enumeration value="waardevolle boom"/>
 *     &lt;enumeration value="water"/>
 *     &lt;enumeration value="waterberging"/>
 *     &lt;enumeration value="waterkering"/>
 *     &lt;enumeration value="waterstaat"/>
 *     &lt;enumeration value="waterweg"/>
 *     &lt;enumeration value="waterzuiveringsinstallatie"/>
 *     &lt;enumeration value="weg"/>
 *     &lt;enumeration value="wellness"/>
 *     &lt;enumeration value="welzijnsinstelling"/>
 *     &lt;enumeration value="wielerbaan"/>
 *     &lt;enumeration value="windturbine"/>
 *     &lt;enumeration value="windturbinepark"/>
 *     &lt;enumeration value="wonen"/>
 *     &lt;enumeration value="woongebied"/>
 *     &lt;enumeration value="woonschepenligplaats"/>
 *     &lt;enumeration value="woonwagenstandplaats"/>
 *     &lt;enumeration value="zee"/>
 *     &lt;enumeration value="zend-/ontvangstinstallatie"/>
 *     &lt;enumeration value="zorginstelling"/>
 *     &lt;enumeration value="zorgboerderij"/>
 *     &lt;enumeration value="zorgwoning"/>
 *     &lt;enumeration value="zwembad"/>
 *     &lt;enumeration value="aanlegsteiger uitgesloten"/>
 *     &lt;enumeration value="agrarisch uitgesloten"/>
 *     &lt;enumeration value="agrarisch bedrijf uitgesloten"/>
 *     &lt;enumeration value="agrarisch loonbedrijf uitgesloten"/>
 *     &lt;enumeration value="agrarisch met waarden uitgesloten"/>
 *     &lt;enumeration value="akkerbouw uitgesloten"/>
 *     &lt;enumeration value="ambachtelijke be- en verwerking agrarische producten uitgesloten"/>
 *     &lt;enumeration value="aquacultuur uitgesloten"/>
 *     &lt;enumeration value="aquaduct uitgesloten"/>
 *     &lt;enumeration value="archeologische waarden uitgesloten"/>
 *     &lt;enumeration value="asielzoekerscentrum uitgesloten"/>
 *     &lt;enumeration value="atelier uitgesloten"/>
 *     &lt;enumeration value="attractiepark uitgesloten"/>
 *     &lt;enumeration value="autocircuit uitgesloten"/>
 *     &lt;enumeration value="baggerspeciedepot uitgesloten"/>
 *     &lt;enumeration value="bed &amp; breakfast uitgesloten"/>
 *     &lt;enumeration value="bedrijf uitgesloten"/>
 *     &lt;enumeration value="bedrijf aan huis uitgesloten"/>
 *     &lt;enumeration value="bedrijfswoning uitgesloten"/>
 *     &lt;enumeration value="bedrijventerrein uitgesloten"/>
 *     &lt;enumeration value="beeldbepalende boom uitgesloten"/>
 *     &lt;enumeration value="begraafplaats uitgesloten"/>
 *     &lt;enumeration value="belwinkel uitgesloten"/>
 *     &lt;enumeration value="beroep aan huis uitgesloten"/>
 *     &lt;enumeration value="bibliotheek uitgesloten"/>
 *     &lt;enumeration value="bioscoop uitgesloten"/>
 *     &lt;enumeration value="bollenteelt uitgesloten"/>
 *     &lt;enumeration value="bomenteelt uitgesloten"/>
 *     &lt;enumeration value="bordeel uitgesloten"/>
 *     &lt;enumeration value="bos uitgesloten"/>
 *     &lt;enumeration value="bowlingbaan uitgesloten"/>
 *     &lt;enumeration value="brandweerkazerne uitgesloten"/>
 *     &lt;enumeration value="brug uitgesloten"/>
 *     &lt;enumeration value="caravanstalling uitgesloten"/>
 *     &lt;enumeration value="casino uitgesloten"/>
 *     &lt;enumeration value="centrum uitgesloten"/>
 *     &lt;enumeration value="congrescentrum uitgesloten"/>
 *     &lt;enumeration value="creativiteitscentrum uitgesloten"/>
 *     &lt;enumeration value="crematorium uitgesloten"/>
 *     &lt;enumeration value="cultuur en ontspanning uitgesloten"/>
 *     &lt;enumeration value="cultuurhistorische waarden uitgesloten"/>
 *     &lt;enumeration value="dagrecreatie uitgesloten"/>
 *     &lt;enumeration value="dansschool uitgesloten"/>
 *     &lt;enumeration value="detailhandel uitgesloten"/>
 *     &lt;enumeration value="detailhandel grootschalig uitgesloten"/>
 *     &lt;enumeration value="detailhandel in brand en explosiegevaarlijke goederen uitgesloten"/>
 *     &lt;enumeration value="detailhandel perifeer uitgesloten"/>
 *     &lt;enumeration value="detailhandel volumineus uitgesloten"/>
 *     &lt;enumeration value="dienstverlening uitgesloten"/>
 *     &lt;enumeration value="dierenasiel uitgesloten"/>
 *     &lt;enumeration value="dierentuin uitgesloten"/>
 *     &lt;enumeration value="discotheek uitgesloten"/>
 *     &lt;enumeration value="drafbaan uitgesloten"/>
 *     &lt;enumeration value="drugsopvang uitgesloten"/>
 *     &lt;enumeration value="ecologische verbindingszone uitgesloten"/>
 *     &lt;enumeration value="ecologische waarde uitgesloten"/>
 *     &lt;enumeration value="eendenkooi uitgesloten"/>
 *     &lt;enumeration value="erf uitgesloten"/>
 *     &lt;enumeration value="evenemententerrein uitgesloten"/>
 *     &lt;enumeration value="feestzaal uitgesloten"/>
 *     &lt;enumeration value="fruitteelt uitgesloten"/>
 *     &lt;enumeration value="garage uitgesloten"/>
 *     &lt;enumeration value="geluidscherm uitgesloten"/>
 *     &lt;enumeration value="geluidwal uitgesloten"/>
 *     &lt;enumeration value="gemaal uitgesloten"/>
 *     &lt;enumeration value="gemengd uitgesloten"/>
 *     &lt;enumeration value="geomorfologische waarde uitgesloten"/>
 *     &lt;enumeration value="gezondheidszorg uitgesloten"/>
 *     &lt;enumeration value="glastuinbouw uitgesloten"/>
 *     &lt;enumeration value="golfbaan uitgesloten"/>
 *     &lt;enumeration value="groen uitgesloten"/>
 *     &lt;enumeration value="gronddepot uitgesloten"/>
 *     &lt;enumeration value="grondgebonden veehouderij uitgesloten"/>
 *     &lt;enumeration value="groothandel uitgesloten"/>
 *     &lt;enumeration value="haven uitgesloten"/>
 *     &lt;enumeration value="horeca uitgesloten"/>
 *     &lt;enumeration value="houtsingel uitgesloten"/>
 *     &lt;enumeration value="houtwal uitgesloten"/>
 *     &lt;enumeration value="hovenier uitgesloten"/>
 *     &lt;enumeration value="ijsbaan uitgesloten"/>
 *     &lt;enumeration value="infrastructuur uitgesloten"/>
 *     &lt;enumeration value="intensieve kwekerij uitgesloten"/>
 *     &lt;enumeration value="intensieve veehouderij uitgesloten"/>
 *     &lt;enumeration value="internetcafé uitgesloten"/>
 *     &lt;enumeration value="internetwinkel uitgesloten"/>
 *     &lt;enumeration value="jachthaven uitgesloten"/>
 *     &lt;enumeration value="jeugdopvang uitgesloten"/>
 *     &lt;enumeration value="jongeren ontmoetingsplek uitgesloten"/>
 *     &lt;enumeration value="justitiële inrichting uitgesloten"/>
 *     &lt;enumeration value="kamerverhuur uitgesloten"/>
 *     &lt;enumeration value="kampeerboerderij uitgesloten"/>
 *     &lt;enumeration value="kampeerterrein uitgesloten"/>
 *     &lt;enumeration value="kantoor uitgesloten"/>
 *     &lt;enumeration value="kartbaan uitgesloten"/>
 *     &lt;enumeration value="kas uitgesloten"/>
 *     &lt;enumeration value="kazerne uitgesloten"/>
 *     &lt;enumeration value="kinderboerderij uitgesloten"/>
 *     &lt;enumeration value="kunstijsbaan uitgesloten"/>
 *     &lt;enumeration value="laad- en losplaats uitgesloten"/>
 *     &lt;enumeration value="landingsbaan uitgesloten"/>
 *     &lt;enumeration value="landschapswaarden uitgesloten"/>
 *     &lt;enumeration value="leidingstrook uitgesloten"/>
 *     &lt;enumeration value="ligplaats uitgesloten"/>
 *     &lt;enumeration value="luchthaven uitgesloten"/>
 *     &lt;enumeration value="luchtverkeer uitgesloten"/>
 *     &lt;enumeration value="maatschappelijk uitgesloten"/>
 *     &lt;enumeration value="manege uitgesloten"/>
 *     &lt;enumeration value="markt uitgesloten"/>
 *     &lt;enumeration value="meer uitgesloten"/>
 *     &lt;enumeration value="militaire zaken uitgesloten"/>
 *     &lt;enumeration value="militair oefenterrein uitgesloten"/>
 *     &lt;enumeration value="modelvliegtuigbaan uitgesloten"/>
 *     &lt;enumeration value="monumentale boom uitgesloten"/>
 *     &lt;enumeration value="motorcrossterrein uitgesloten"/>
 *     &lt;enumeration value="munitiedepot uitgesloten"/>
 *     &lt;enumeration value="museum uitgesloten"/>
 *     &lt;enumeration value="muziekschool uitgesloten"/>
 *     &lt;enumeration value="muziektheater uitgesloten"/>
 *     &lt;enumeration value="naschoolse opvang uitgesloten"/>
 *     &lt;enumeration value="natuur- en landschapswaarden uitgesloten"/>
 *     &lt;enumeration value="natuur uitgesloten"/>
 *     &lt;enumeration value="natuurwaarden uitgesloten"/>
 *     &lt;enumeration value="nutsbedrijf uitgesloten"/>
 *     &lt;enumeration value="nutsvoorziening uitgesloten"/>
 *     &lt;enumeration value="oever uitgesloten"/>
 *     &lt;enumeration value="onderwijs uitgesloten"/>
 *     &lt;enumeration value="ontsluiting uitgesloten"/>
 *     &lt;enumeration value="openbaar vervoer uitgesloten"/>
 *     &lt;enumeration value="openbare dienstverlening uitgesloten"/>
 *     &lt;enumeration value="opslag uitgesloten"/>
 *     &lt;enumeration value="openbaar vervoerstation uitgesloten"/>
 *     &lt;enumeration value="paardenfokkerij uitgesloten"/>
 *     &lt;enumeration value="paardenhouderij uitgesloten"/>
 *     &lt;enumeration value="pad uitgesloten"/>
 *     &lt;enumeration value="park uitgesloten"/>
 *     &lt;enumeration value="parkeergarage uitgesloten"/>
 *     &lt;enumeration value="parkeerterrein uitgesloten"/>
 *     &lt;enumeration value="partyboerderij uitgesloten"/>
 *     &lt;enumeration value="passantenhaven uitgesloten"/>
 *     &lt;enumeration value="pitch &amp; putt uitgesloten"/>
 *     &lt;enumeration value="plantsoen uitgesloten"/>
 *     &lt;enumeration value="plein uitgesloten"/>
 *     &lt;enumeration value="praktijkruimte uitgesloten"/>
 *     &lt;enumeration value="prostitutie uitgesloten"/>
 *     &lt;enumeration value="raamprostitutie (raamexploitatie) uitgesloten"/>
 *     &lt;enumeration value="railverkeer uitgesloten"/>
 *     &lt;enumeration value="recreatie uitgesloten"/>
 *     &lt;enumeration value="recreatiewoning uitgesloten"/>
 *     &lt;enumeration value="religie uitgesloten"/>
 *     &lt;enumeration value="risicovolle inrichting uitgesloten"/>
 *     &lt;enumeration value="rivier uitgesloten"/>
 *     &lt;enumeration value="sauna uitgesloten"/>
 *     &lt;enumeration value="schiphuis uitgesloten"/>
 *     &lt;enumeration value="seksinrichting uitgesloten"/>
 *     &lt;enumeration value="sierteelt uitgesloten"/>
 *     &lt;enumeration value="silo uitgesloten"/>
 *     &lt;enumeration value="skeelerbaan uitgesloten"/>
 *     &lt;enumeration value="skibaan uitgesloten"/>
 *     &lt;enumeration value="sluis uitgesloten"/>
 *     &lt;enumeration value="speeltuin uitgesloten"/>
 *     &lt;enumeration value="speelvoorziening uitgesloten"/>
 *     &lt;enumeration value="spoorweg uitgesloten"/>
 *     &lt;enumeration value="sport uitgesloten"/>
 *     &lt;enumeration value="sportcentrum uitgesloten"/>
 *     &lt;enumeration value="sporthal uitgesloten"/>
 *     &lt;enumeration value="sportveld uitgesloten"/>
 *     &lt;enumeration value="sportzaal uitgesloten"/>
 *     &lt;enumeration value="squashcentrum uitgesloten"/>
 *     &lt;enumeration value="stadion uitgesloten"/>
 *     &lt;enumeration value="steiger uitgesloten"/>
 *     &lt;enumeration value="strand uitgesloten"/>
 *     &lt;enumeration value="strandhuis uitgesloten"/>
 *     &lt;enumeration value="studentenhuisvesting uitgesloten"/>
 *     &lt;enumeration value="stuw uitgesloten"/>
 *     &lt;enumeration value="supermarkt uitgesloten"/>
 *     &lt;enumeration value="tennisbaan uitgesloten"/>
 *     &lt;enumeration value="terras uitgesloten"/>
 *     &lt;enumeration value="theater uitgesloten"/>
 *     &lt;enumeration value="tuin uitgesloten"/>
 *     &lt;enumeration value="tuinbouw uitgesloten"/>
 *     &lt;enumeration value="tuincentrum uitgesloten"/>
 *     &lt;enumeration value="tunnel uitgesloten"/>
 *     &lt;enumeration value="uitvaartcentrum uitgesloten"/>
 *     &lt;enumeration value="vaarweg uitgesloten"/>
 *     &lt;enumeration value="veerhaven uitgesloten"/>
 *     &lt;enumeration value="ven uitgesloten"/>
 *     &lt;enumeration value="verblijfsgebied uitgesloten"/>
 *     &lt;enumeration value="verblijfsrecreatie uitgesloten"/>
 *     &lt;enumeration value="verenigingsleven uitgesloten"/>
 *     &lt;enumeration value="verkeer uitgesloten"/>
 *     &lt;enumeration value="verkoop eigen producten uitgesloten"/>
 *     &lt;enumeration value="verkooppunt motorbrandstoffen met lpg uitgesloten"/>
 *     &lt;enumeration value="verkooppunt motorbrandstoffen zonder lpg uitgesloten"/>
 *     &lt;enumeration value="vertrek- en aankomsthal uitgesloten"/>
 *     &lt;enumeration value="vijver uitgesloten"/>
 *     &lt;enumeration value="viskwekerij uitgesloten"/>
 *     &lt;enumeration value="volkstuin uitgesloten"/>
 *     &lt;enumeration value="vulpunt lpg uitgesloten"/>
 *     &lt;enumeration value="waardevolle boom uitgesloten"/>
 *     &lt;enumeration value="water uitgesloten"/>
 *     &lt;enumeration value="waterberging uitgesloten"/>
 *     &lt;enumeration value="waterkering uitgesloten"/>
 *     &lt;enumeration value="waterstaat uitgesloten"/>
 *     &lt;enumeration value="waterweg uitgesloten"/>
 *     &lt;enumeration value="waterzuiveringsinstallatie uitgesloten"/>
 *     &lt;enumeration value="weg uitgesloten"/>
 *     &lt;enumeration value="wellness uitgesloten"/>
 *     &lt;enumeration value="welzijnsinstelling uitgesloten"/>
 *     &lt;enumeration value="wielerbaan uitgesloten"/>
 *     &lt;enumeration value="windturbine uitgesloten"/>
 *     &lt;enumeration value="windturbinepark uitgesloten"/>
 *     &lt;enumeration value="wonen uitgesloten"/>
 *     &lt;enumeration value="woongebied uitgesloten"/>
 *     &lt;enumeration value="woonschepenligplaats uitgesloten"/>
 *     &lt;enumeration value="woonwagenstandplaats uitgesloten"/>
 *     &lt;enumeration value="zee uitgesloten"/>
 *     &lt;enumeration value="zend-/ontvangstinstallatie uitgesloten"/>
 *     &lt;enumeration value="zorginstelling uitgesloten"/>
 *     &lt;enumeration value="zorgboerderij uitgesloten"/>
 *     &lt;enumeration value="zorgwoning uitgesloten"/>
 *     &lt;enumeration value="zwembad uitgesloten"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FunctieaanduidingenEnumerationType")
@XmlEnum
public enum FunctieaanduidingenEnumerationType {

    @XmlEnumValue("aanlegsteiger")
    AANLEGSTEIGER("aanlegsteiger"),
    @XmlEnumValue("agrarisch")
    AGRARISCH("agrarisch"),
    @XmlEnumValue("agrarisch bedrijf")
    AGRARISCH_BEDRIJF("agrarisch bedrijf"),
    @XmlEnumValue("agrarisch loonbedrijf")
    AGRARISCH_LOONBEDRIJF("agrarisch loonbedrijf"),
    @XmlEnumValue("agrarisch met waarden")
    AGRARISCH_MET_WAARDEN("agrarisch met waarden"),
    @XmlEnumValue("akkerbouw")
    AKKERBOUW("akkerbouw"),
    @XmlEnumValue("ambachtelijke be- en verwerking agrarische producten")
    AMBACHTELIJKE_BE_EN_VERWERKING_AGRARISCHE_PRODUCTEN("ambachtelijke be- en verwerking agrarische producten"),
    @XmlEnumValue("aquacultuur")
    AQUACULTUUR("aquacultuur"),
    @XmlEnumValue("aquaduct")
    AQUADUCT("aquaduct"),
    @XmlEnumValue("archeologische waarden")
    ARCHEOLOGISCHE_WAARDEN("archeologische waarden"),
    @XmlEnumValue("asielzoekerscentrum")
    ASIELZOEKERSCENTRUM("asielzoekerscentrum"),
    @XmlEnumValue("atelier")
    ATELIER("atelier"),
    @XmlEnumValue("attractiepark")
    ATTRACTIEPARK("attractiepark"),
    @XmlEnumValue("autocircuit")
    AUTOCIRCUIT("autocircuit"),
    @XmlEnumValue("baggerspeciedepot")
    BAGGERSPECIEDEPOT("baggerspeciedepot"),
    @XmlEnumValue("bed & breakfast")
    BED_BREAKFAST("bed & breakfast"),
    @XmlEnumValue("bedrijf")
    BEDRIJF("bedrijf"),
    @XmlEnumValue("bedrijf aan huis")
    BEDRIJF_AAN_HUIS("bedrijf aan huis"),
    @XmlEnumValue("bedrijfswoning")
    BEDRIJFSWONING("bedrijfswoning"),
    @XmlEnumValue("bedrijventerrein")
    BEDRIJVENTERREIN("bedrijventerrein"),
    @XmlEnumValue("beeldbepalende boom")
    BEELDBEPALENDE_BOOM("beeldbepalende boom"),
    @XmlEnumValue("begraafplaats")
    BEGRAAFPLAATS("begraafplaats"),
    @XmlEnumValue("belwinkel")
    BELWINKEL("belwinkel"),
    @XmlEnumValue("beroep aan huis")
    BEROEP_AAN_HUIS("beroep aan huis"),
    @XmlEnumValue("bibliotheek")
    BIBLIOTHEEK("bibliotheek"),
    @XmlEnumValue("bioscoop")
    BIOSCOOP("bioscoop"),
    @XmlEnumValue("bollenteelt")
    BOLLENTEELT("bollenteelt"),
    @XmlEnumValue("bomenteelt")
    BOMENTEELT("bomenteelt"),
    @XmlEnumValue("bordeel")
    BORDEEL("bordeel"),
    @XmlEnumValue("bos")
    BOS("bos"),
    @XmlEnumValue("bowlingbaan")
    BOWLINGBAAN("bowlingbaan"),
    @XmlEnumValue("brandweerkazerne")
    BRANDWEERKAZERNE("brandweerkazerne"),
    @XmlEnumValue("brug")
    BRUG("brug"),
    @XmlEnumValue("caravanstalling")
    CARAVANSTALLING("caravanstalling"),
    @XmlEnumValue("casino")
    CASINO("casino"),
    @XmlEnumValue("centrum")
    CENTRUM("centrum"),
    @XmlEnumValue("congrescentrum")
    CONGRESCENTRUM("congrescentrum"),
    @XmlEnumValue("creativiteitscentrum")
    CREATIVITEITSCENTRUM("creativiteitscentrum"),
    @XmlEnumValue("crematorium")
    CREMATORIUM("crematorium"),
    @XmlEnumValue("cultuur en ontspanning")
    CULTUUR_EN_ONTSPANNING("cultuur en ontspanning"),
    @XmlEnumValue("cultuurhistorische waarden")
    CULTUURHISTORISCHE_WAARDEN("cultuurhistorische waarden"),
    @XmlEnumValue("dagrecreatie")
    DAGRECREATIE("dagrecreatie"),
    @XmlEnumValue("dansschool")
    DANSSCHOOL("dansschool"),
    @XmlEnumValue("detailhandel")
    DETAILHANDEL("detailhandel"),
    @XmlEnumValue("detailhandel grootschalig")
    DETAILHANDEL_GROOTSCHALIG("detailhandel grootschalig"),
    @XmlEnumValue("detailhandel in brand en explosiegevaarlijke goederen")
    DETAILHANDEL_IN_BRAND_EN_EXPLOSIEGEVAARLIJKE_GOEDEREN("detailhandel in brand en explosiegevaarlijke goederen"),
    @XmlEnumValue("detailhandel perifeer")
    DETAILHANDEL_PERIFEER("detailhandel perifeer"),
    @XmlEnumValue("detailhandel volumineus")
    DETAILHANDEL_VOLUMINEUS("detailhandel volumineus"),
    @XmlEnumValue("dienstverlening")
    DIENSTVERLENING("dienstverlening"),
    @XmlEnumValue("dierenasiel")
    DIERENASIEL("dierenasiel"),
    @XmlEnumValue("dierentuin")
    DIERENTUIN("dierentuin"),
    @XmlEnumValue("discotheek")
    DISCOTHEEK("discotheek"),
    @XmlEnumValue("drafbaan")
    DRAFBAAN("drafbaan"),
    @XmlEnumValue("drugsopvang")
    DRUGSOPVANG("drugsopvang"),
    @XmlEnumValue("ecologische verbindingszone")
    ECOLOGISCHE_VERBINDINGSZONE("ecologische verbindingszone"),
    @XmlEnumValue("ecologische waarde")
    ECOLOGISCHE_WAARDE("ecologische waarde"),
    @XmlEnumValue("eendenkooi")
    EENDENKOOI("eendenkooi"),
    @XmlEnumValue("erf")
    ERF("erf"),
    @XmlEnumValue("evenemententerrein")
    EVENEMENTENTERREIN("evenemententerrein"),
    @XmlEnumValue("feestzaal")
    FEESTZAAL("feestzaal"),
    @XmlEnumValue("fruitteelt")
    FRUITTEELT("fruitteelt"),
    @XmlEnumValue("garage")
    GARAGE("garage"),
    @XmlEnumValue("geluidscherm")
    GELUIDSCHERM("geluidscherm"),
    @XmlEnumValue("geluidwal")
    GELUIDWAL("geluidwal"),
    @XmlEnumValue("gemaal")
    GEMAAL("gemaal"),
    @XmlEnumValue("gemengd")
    GEMENGD("gemengd"),
    @XmlEnumValue("geomorfologische waarde")
    GEOMORFOLOGISCHE_WAARDE("geomorfologische waarde"),
    @XmlEnumValue("gezondheidszorg")
    GEZONDHEIDSZORG("gezondheidszorg"),
    @XmlEnumValue("glastuinbouw")
    GLASTUINBOUW("glastuinbouw"),
    @XmlEnumValue("golfbaan")
    GOLFBAAN("golfbaan"),
    @XmlEnumValue("groen")
    GROEN("groen"),
    @XmlEnumValue("gronddepot")
    GRONDDEPOT("gronddepot"),
    @XmlEnumValue("grondgebonden veehouderij")
    GRONDGEBONDEN_VEEHOUDERIJ("grondgebonden veehouderij"),
    @XmlEnumValue("groothandel")
    GROOTHANDEL("groothandel"),
    @XmlEnumValue("haven")
    HAVEN("haven"),
    @XmlEnumValue("horeca")
    HORECA("horeca"),
    @XmlEnumValue("houtsingel")
    HOUTSINGEL("houtsingel"),
    @XmlEnumValue("houtwal")
    HOUTWAL("houtwal"),
    @XmlEnumValue("hovenier")
    HOVENIER("hovenier"),
    @XmlEnumValue("ijsbaan")
    IJSBAAN("ijsbaan"),
    @XmlEnumValue("infrastructuur")
    INFRASTRUCTUUR("infrastructuur"),
    @XmlEnumValue("intensieve kwekerij")
    INTENSIEVE_KWEKERIJ("intensieve kwekerij"),
    @XmlEnumValue("intensieve veehouderij")
    INTENSIEVE_VEEHOUDERIJ("intensieve veehouderij"),
    @XmlEnumValue("internetcaf\u00e9")
    INTERNETCAFÉ("internetcaf\u00e9"),
    @XmlEnumValue("internetwinkel")
    INTERNETWINKEL("internetwinkel"),
    @XmlEnumValue("jachthaven")
    JACHTHAVEN("jachthaven"),
    @XmlEnumValue("jeugdopvang")
    JEUGDOPVANG("jeugdopvang"),
    @XmlEnumValue("jongeren ontmoetingsplek")
    JONGEREN_ONTMOETINGSPLEK("jongeren ontmoetingsplek"),
    @XmlEnumValue("justiti\u00eble inrichting")
    JUSTITIËLE_INRICHTING("justiti\u00eble inrichting"),
    @XmlEnumValue("kamerverhuur")
    KAMERVERHUUR("kamerverhuur"),
    @XmlEnumValue("kampeerboerderij")
    KAMPEERBOERDERIJ("kampeerboerderij"),
    @XmlEnumValue("kampeerterrein")
    KAMPEERTERREIN("kampeerterrein"),
    @XmlEnumValue("kantoor")
    KANTOOR("kantoor"),
    @XmlEnumValue("kartbaan")
    KARTBAAN("kartbaan"),
    @XmlEnumValue("kas")
    KAS("kas"),
    @XmlEnumValue("kazerne")
    KAZERNE("kazerne"),
    @XmlEnumValue("kinderboerderij")
    KINDERBOERDERIJ("kinderboerderij"),
    @XmlEnumValue("kunstijsbaan")
    KUNSTIJSBAAN("kunstijsbaan"),
    @XmlEnumValue("laad- en losplaats")
    LAAD_EN_LOSPLAATS("laad- en losplaats"),
    @XmlEnumValue("landingsbaan")
    LANDINGSBAAN("landingsbaan"),
    @XmlEnumValue("landschapswaarden")
    LANDSCHAPSWAARDEN("landschapswaarden"),
    @XmlEnumValue("leidingstrook")
    LEIDINGSTROOK("leidingstrook"),
    @XmlEnumValue("ligplaats")
    LIGPLAATS("ligplaats"),
    @XmlEnumValue("luchthaven")
    LUCHTHAVEN("luchthaven"),
    @XmlEnumValue("luchtverkeer")
    LUCHTVERKEER("luchtverkeer"),
    @XmlEnumValue("maatschappelijk")
    MAATSCHAPPELIJK("maatschappelijk"),
    @XmlEnumValue("manege")
    MANEGE("manege"),
    @XmlEnumValue("markt")
    MARKT("markt"),
    @XmlEnumValue("meer")
    MEER("meer"),
    @XmlEnumValue("militaire zaken")
    MILITAIRE_ZAKEN("militaire zaken"),
    @XmlEnumValue("militair oefenterrein")
    MILITAIR_OEFENTERREIN("militair oefenterrein"),
    @XmlEnumValue("modelvliegtuigbaan")
    MODELVLIEGTUIGBAAN("modelvliegtuigbaan"),
    @XmlEnumValue("monumentale boom")
    MONUMENTALE_BOOM("monumentale boom"),
    @XmlEnumValue("motorcrossterrein")
    MOTORCROSSTERREIN("motorcrossterrein"),
    @XmlEnumValue("munitiedepot")
    MUNITIEDEPOT("munitiedepot"),
    @XmlEnumValue("museum")
    MUSEUM("museum"),
    @XmlEnumValue("muziekschool")
    MUZIEKSCHOOL("muziekschool"),
    @XmlEnumValue("muziektheater")
    MUZIEKTHEATER("muziektheater"),
    @XmlEnumValue("naschoolse opvang")
    NASCHOOLSE_OPVANG("naschoolse opvang"),
    @XmlEnumValue("natuur- en landschapswaarden")
    NATUUR_EN_LANDSCHAPSWAARDEN("natuur- en landschapswaarden"),
    @XmlEnumValue("natuur")
    NATUUR("natuur"),
    @XmlEnumValue("natuurwaarden")
    NATUURWAARDEN("natuurwaarden"),
    @XmlEnumValue("nutsbedrijf")
    NUTSBEDRIJF("nutsbedrijf"),
    @XmlEnumValue("nutsvoorziening")
    NUTSVOORZIENING("nutsvoorziening"),
    @XmlEnumValue("oever")
    OEVER("oever"),
    @XmlEnumValue("onderwijs")
    ONDERWIJS("onderwijs"),
    @XmlEnumValue("ontsluiting")
    ONTSLUITING("ontsluiting"),
    @XmlEnumValue("openbaar vervoer")
    OPENBAAR_VERVOER("openbaar vervoer"),
    @XmlEnumValue("openbare dienstverlening")
    OPENBARE_DIENSTVERLENING("openbare dienstverlening"),
    @XmlEnumValue("opslag")
    OPSLAG("opslag"),
    @XmlEnumValue("openbaar vervoerstation")
    OPENBAAR_VERVOERSTATION("openbaar vervoerstation"),
    @XmlEnumValue("paardenfokkerij")
    PAARDENFOKKERIJ("paardenfokkerij"),
    @XmlEnumValue("paardenhouderij")
    PAARDENHOUDERIJ("paardenhouderij"),
    @XmlEnumValue("pad")
    PAD("pad"),
    @XmlEnumValue("park")
    PARK("park"),
    @XmlEnumValue("parkeergarage")
    PARKEERGARAGE("parkeergarage"),
    @XmlEnumValue("parkeerterrein")
    PARKEERTERREIN("parkeerterrein"),
    @XmlEnumValue("partyboerderij")
    PARTYBOERDERIJ("partyboerderij"),
    @XmlEnumValue("passantenhaven")
    PASSANTENHAVEN("passantenhaven"),
    @XmlEnumValue("pitch & putt")
    PITCH_PUTT("pitch & putt"),
    @XmlEnumValue("plantsoen")
    PLANTSOEN("plantsoen"),
    @XmlEnumValue("plein")
    PLEIN("plein"),
    @XmlEnumValue("praktijkruimte")
    PRAKTIJKRUIMTE("praktijkruimte"),
    @XmlEnumValue("prostitutie")
    PROSTITUTIE("prostitutie"),
    @XmlEnumValue("raamprostitutie (raamexploitatie)")
    RAAMPROSTITUTIE_RAAMEXPLOITATIE("raamprostitutie (raamexploitatie)"),
    @XmlEnumValue("railverkeer")
    RAILVERKEER("railverkeer"),
    @XmlEnumValue("recreatie")
    RECREATIE("recreatie"),
    @XmlEnumValue("recreatiewoning")
    RECREATIEWONING("recreatiewoning"),
    @XmlEnumValue("religie")
    RELIGIE("religie"),
    @XmlEnumValue("risicovolle inrichting")
    RISICOVOLLE_INRICHTING("risicovolle inrichting"),
    @XmlEnumValue("rivier")
    RIVIER("rivier"),
    @XmlEnumValue("sauna")
    SAUNA("sauna"),
    @XmlEnumValue("schiphuis")
    SCHIPHUIS("schiphuis"),
    @XmlEnumValue("seksinrichting")
    SEKSINRICHTING("seksinrichting"),
    @XmlEnumValue("sierteelt")
    SIERTEELT("sierteelt"),
    @XmlEnumValue("silo")
    SILO("silo"),
    @XmlEnumValue("skeelerbaan")
    SKEELERBAAN("skeelerbaan"),
    @XmlEnumValue("skibaan")
    SKIBAAN("skibaan"),
    @XmlEnumValue("sluis")
    SLUIS("sluis"),
    @XmlEnumValue("speeltuin")
    SPEELTUIN("speeltuin"),
    @XmlEnumValue("speelvoorziening")
    SPEELVOORZIENING("speelvoorziening"),
    @XmlEnumValue("spoorweg")
    SPOORWEG("spoorweg"),
    @XmlEnumValue("sport")
    SPORT("sport"),
    @XmlEnumValue("sportcentrum")
    SPORTCENTRUM("sportcentrum"),
    @XmlEnumValue("sporthal")
    SPORTHAL("sporthal"),
    @XmlEnumValue("sportveld")
    SPORTVELD("sportveld"),
    @XmlEnumValue("sportzaal")
    SPORTZAAL("sportzaal"),
    @XmlEnumValue("squashcentrum")
    SQUASHCENTRUM("squashcentrum"),
    @XmlEnumValue("stadion")
    STADION("stadion"),
    @XmlEnumValue("steiger")
    STEIGER("steiger"),
    @XmlEnumValue("strand")
    STRAND("strand"),
    @XmlEnumValue("strandhuis")
    STRANDHUIS("strandhuis"),
    @XmlEnumValue("studentenhuisvesting")
    STUDENTENHUISVESTING("studentenhuisvesting"),
    @XmlEnumValue("stuw")
    STUW("stuw"),
    @XmlEnumValue("supermarkt")
    SUPERMARKT("supermarkt"),
    @XmlEnumValue("tennisbaan")
    TENNISBAAN("tennisbaan"),
    @XmlEnumValue("terras")
    TERRAS("terras"),
    @XmlEnumValue("theater")
    THEATER("theater"),
    @XmlEnumValue("tuin")
    TUIN("tuin"),
    @XmlEnumValue("tuinbouw")
    TUINBOUW("tuinbouw"),
    @XmlEnumValue("tuincentrum")
    TUINCENTRUM("tuincentrum"),
    @XmlEnumValue("tunnel")
    TUNNEL("tunnel"),
    @XmlEnumValue("uitvaartcentrum")
    UITVAARTCENTRUM("uitvaartcentrum"),
    @XmlEnumValue("vaarweg")
    VAARWEG("vaarweg"),
    @XmlEnumValue("veerhaven")
    VEERHAVEN("veerhaven"),
    @XmlEnumValue("ven")
    VEN("ven"),
    @XmlEnumValue("verblijfsgebied")
    VERBLIJFSGEBIED("verblijfsgebied"),
    @XmlEnumValue("verblijfsrecreatie")
    VERBLIJFSRECREATIE("verblijfsrecreatie"),
    @XmlEnumValue("verenigingsleven")
    VERENIGINGSLEVEN("verenigingsleven"),
    @XmlEnumValue("verkeer")
    VERKEER("verkeer"),
    @XmlEnumValue("verkoop eigen producten")
    VERKOOP_EIGEN_PRODUCTEN("verkoop eigen producten"),
    @XmlEnumValue("verkooppunt motorbrandstoffen met lpg")
    VERKOOPPUNT_MOTORBRANDSTOFFEN_MET_LPG("verkooppunt motorbrandstoffen met lpg"),
    @XmlEnumValue("verkooppunt motorbrandstoffen zonder lpg")
    VERKOOPPUNT_MOTORBRANDSTOFFEN_ZONDER_LPG("verkooppunt motorbrandstoffen zonder lpg"),
    @XmlEnumValue("vertrek- en aankomsthal")
    VERTREK_EN_AANKOMSTHAL("vertrek- en aankomsthal"),
    @XmlEnumValue("vijver")
    VIJVER("vijver"),
    @XmlEnumValue("viskwekerij")
    VISKWEKERIJ("viskwekerij"),
    @XmlEnumValue("volkstuin")
    VOLKSTUIN("volkstuin"),
    @XmlEnumValue("vulpunt lpg")
    VULPUNT_LPG("vulpunt lpg"),
    @XmlEnumValue("waardevolle boom")
    WAARDEVOLLE_BOOM("waardevolle boom"),
    @XmlEnumValue("water")
    WATER("water"),
    @XmlEnumValue("waterberging")
    WATERBERGING("waterberging"),
    @XmlEnumValue("waterkering")
    WATERKERING("waterkering"),
    @XmlEnumValue("waterstaat")
    WATERSTAAT("waterstaat"),
    @XmlEnumValue("waterweg")
    WATERWEG("waterweg"),
    @XmlEnumValue("waterzuiveringsinstallatie")
    WATERZUIVERINGSINSTALLATIE("waterzuiveringsinstallatie"),
    @XmlEnumValue("weg")
    WEG("weg"),
    @XmlEnumValue("wellness")
    WELLNESS("wellness"),
    @XmlEnumValue("welzijnsinstelling")
    WELZIJNSINSTELLING("welzijnsinstelling"),
    @XmlEnumValue("wielerbaan")
    WIELERBAAN("wielerbaan"),
    @XmlEnumValue("windturbine")
    WINDTURBINE("windturbine"),
    @XmlEnumValue("windturbinepark")
    WINDTURBINEPARK("windturbinepark"),
    @XmlEnumValue("wonen")
    WONEN("wonen"),
    @XmlEnumValue("woongebied")
    WOONGEBIED("woongebied"),
    @XmlEnumValue("woonschepenligplaats")
    WOONSCHEPENLIGPLAATS("woonschepenligplaats"),
    @XmlEnumValue("woonwagenstandplaats")
    WOONWAGENSTANDPLAATS("woonwagenstandplaats"),
    @XmlEnumValue("zee")
    ZEE("zee"),
    @XmlEnumValue("zend-/ontvangstinstallatie")
    ZEND_ONTVANGSTINSTALLATIE("zend-/ontvangstinstallatie"),
    @XmlEnumValue("zorginstelling")
    ZORGINSTELLING("zorginstelling"),
    @XmlEnumValue("zorgboerderij")
    ZORGBOERDERIJ("zorgboerderij"),
    @XmlEnumValue("zorgwoning")
    ZORGWONING("zorgwoning"),
    @XmlEnumValue("zwembad")
    ZWEMBAD("zwembad"),
    @XmlEnumValue("aanlegsteiger uitgesloten")
    AANLEGSTEIGER_UITGESLOTEN("aanlegsteiger uitgesloten"),
    @XmlEnumValue("agrarisch uitgesloten")
    AGRARISCH_UITGESLOTEN("agrarisch uitgesloten"),
    @XmlEnumValue("agrarisch bedrijf uitgesloten")
    AGRARISCH_BEDRIJF_UITGESLOTEN("agrarisch bedrijf uitgesloten"),
    @XmlEnumValue("agrarisch loonbedrijf uitgesloten")
    AGRARISCH_LOONBEDRIJF_UITGESLOTEN("agrarisch loonbedrijf uitgesloten"),
    @XmlEnumValue("agrarisch met waarden uitgesloten")
    AGRARISCH_MET_WAARDEN_UITGESLOTEN("agrarisch met waarden uitgesloten"),
    @XmlEnumValue("akkerbouw uitgesloten")
    AKKERBOUW_UITGESLOTEN("akkerbouw uitgesloten"),
    @XmlEnumValue("ambachtelijke be- en verwerking agrarische producten uitgesloten")
    AMBACHTELIJKE_BE_EN_VERWERKING_AGRARISCHE_PRODUCTEN_UITGESLOTEN("ambachtelijke be- en verwerking agrarische producten uitgesloten"),
    @XmlEnumValue("aquacultuur uitgesloten")
    AQUACULTUUR_UITGESLOTEN("aquacultuur uitgesloten"),
    @XmlEnumValue("aquaduct uitgesloten")
    AQUADUCT_UITGESLOTEN("aquaduct uitgesloten"),
    @XmlEnumValue("archeologische waarden uitgesloten")
    ARCHEOLOGISCHE_WAARDEN_UITGESLOTEN("archeologische waarden uitgesloten"),
    @XmlEnumValue("asielzoekerscentrum uitgesloten")
    ASIELZOEKERSCENTRUM_UITGESLOTEN("asielzoekerscentrum uitgesloten"),
    @XmlEnumValue("atelier uitgesloten")
    ATELIER_UITGESLOTEN("atelier uitgesloten"),
    @XmlEnumValue("attractiepark uitgesloten")
    ATTRACTIEPARK_UITGESLOTEN("attractiepark uitgesloten"),
    @XmlEnumValue("autocircuit uitgesloten")
    AUTOCIRCUIT_UITGESLOTEN("autocircuit uitgesloten"),
    @XmlEnumValue("baggerspeciedepot uitgesloten")
    BAGGERSPECIEDEPOT_UITGESLOTEN("baggerspeciedepot uitgesloten"),
    @XmlEnumValue("bed & breakfast uitgesloten")
    BED_BREAKFAST_UITGESLOTEN("bed & breakfast uitgesloten"),
    @XmlEnumValue("bedrijf uitgesloten")
    BEDRIJF_UITGESLOTEN("bedrijf uitgesloten"),
    @XmlEnumValue("bedrijf aan huis uitgesloten")
    BEDRIJF_AAN_HUIS_UITGESLOTEN("bedrijf aan huis uitgesloten"),
    @XmlEnumValue("bedrijfswoning uitgesloten")
    BEDRIJFSWONING_UITGESLOTEN("bedrijfswoning uitgesloten"),
    @XmlEnumValue("bedrijventerrein uitgesloten")
    BEDRIJVENTERREIN_UITGESLOTEN("bedrijventerrein uitgesloten"),
    @XmlEnumValue("beeldbepalende boom uitgesloten")
    BEELDBEPALENDE_BOOM_UITGESLOTEN("beeldbepalende boom uitgesloten"),
    @XmlEnumValue("begraafplaats uitgesloten")
    BEGRAAFPLAATS_UITGESLOTEN("begraafplaats uitgesloten"),
    @XmlEnumValue("belwinkel uitgesloten")
    BELWINKEL_UITGESLOTEN("belwinkel uitgesloten"),
    @XmlEnumValue("beroep aan huis uitgesloten")
    BEROEP_AAN_HUIS_UITGESLOTEN("beroep aan huis uitgesloten"),
    @XmlEnumValue("bibliotheek uitgesloten")
    BIBLIOTHEEK_UITGESLOTEN("bibliotheek uitgesloten"),
    @XmlEnumValue("bioscoop uitgesloten")
    BIOSCOOP_UITGESLOTEN("bioscoop uitgesloten"),
    @XmlEnumValue("bollenteelt uitgesloten")
    BOLLENTEELT_UITGESLOTEN("bollenteelt uitgesloten"),
    @XmlEnumValue("bomenteelt uitgesloten")
    BOMENTEELT_UITGESLOTEN("bomenteelt uitgesloten"),
    @XmlEnumValue("bordeel uitgesloten")
    BORDEEL_UITGESLOTEN("bordeel uitgesloten"),
    @XmlEnumValue("bos uitgesloten")
    BOS_UITGESLOTEN("bos uitgesloten"),
    @XmlEnumValue("bowlingbaan uitgesloten")
    BOWLINGBAAN_UITGESLOTEN("bowlingbaan uitgesloten"),
    @XmlEnumValue("brandweerkazerne uitgesloten")
    BRANDWEERKAZERNE_UITGESLOTEN("brandweerkazerne uitgesloten"),
    @XmlEnumValue("brug uitgesloten")
    BRUG_UITGESLOTEN("brug uitgesloten"),
    @XmlEnumValue("caravanstalling uitgesloten")
    CARAVANSTALLING_UITGESLOTEN("caravanstalling uitgesloten"),
    @XmlEnumValue("casino uitgesloten")
    CASINO_UITGESLOTEN("casino uitgesloten"),
    @XmlEnumValue("centrum uitgesloten")
    CENTRUM_UITGESLOTEN("centrum uitgesloten"),
    @XmlEnumValue("congrescentrum uitgesloten")
    CONGRESCENTRUM_UITGESLOTEN("congrescentrum uitgesloten"),
    @XmlEnumValue("creativiteitscentrum uitgesloten")
    CREATIVITEITSCENTRUM_UITGESLOTEN("creativiteitscentrum uitgesloten"),
    @XmlEnumValue("crematorium uitgesloten")
    CREMATORIUM_UITGESLOTEN("crematorium uitgesloten"),
    @XmlEnumValue("cultuur en ontspanning uitgesloten")
    CULTUUR_EN_ONTSPANNING_UITGESLOTEN("cultuur en ontspanning uitgesloten"),
    @XmlEnumValue("cultuurhistorische waarden uitgesloten")
    CULTUURHISTORISCHE_WAARDEN_UITGESLOTEN("cultuurhistorische waarden uitgesloten"),
    @XmlEnumValue("dagrecreatie uitgesloten")
    DAGRECREATIE_UITGESLOTEN("dagrecreatie uitgesloten"),
    @XmlEnumValue("dansschool uitgesloten")
    DANSSCHOOL_UITGESLOTEN("dansschool uitgesloten"),
    @XmlEnumValue("detailhandel uitgesloten")
    DETAILHANDEL_UITGESLOTEN("detailhandel uitgesloten"),
    @XmlEnumValue("detailhandel grootschalig uitgesloten")
    DETAILHANDEL_GROOTSCHALIG_UITGESLOTEN("detailhandel grootschalig uitgesloten"),
    @XmlEnumValue("detailhandel in brand en explosiegevaarlijke goederen uitgesloten")
    DETAILHANDEL_IN_BRAND_EN_EXPLOSIEGEVAARLIJKE_GOEDEREN_UITGESLOTEN("detailhandel in brand en explosiegevaarlijke goederen uitgesloten"),
    @XmlEnumValue("detailhandel perifeer uitgesloten")
    DETAILHANDEL_PERIFEER_UITGESLOTEN("detailhandel perifeer uitgesloten"),
    @XmlEnumValue("detailhandel volumineus uitgesloten")
    DETAILHANDEL_VOLUMINEUS_UITGESLOTEN("detailhandel volumineus uitgesloten"),
    @XmlEnumValue("dienstverlening uitgesloten")
    DIENSTVERLENING_UITGESLOTEN("dienstverlening uitgesloten"),
    @XmlEnumValue("dierenasiel uitgesloten")
    DIERENASIEL_UITGESLOTEN("dierenasiel uitgesloten"),
    @XmlEnumValue("dierentuin uitgesloten")
    DIERENTUIN_UITGESLOTEN("dierentuin uitgesloten"),
    @XmlEnumValue("discotheek uitgesloten")
    DISCOTHEEK_UITGESLOTEN("discotheek uitgesloten"),
    @XmlEnumValue("drafbaan uitgesloten")
    DRAFBAAN_UITGESLOTEN("drafbaan uitgesloten"),
    @XmlEnumValue("drugsopvang uitgesloten")
    DRUGSOPVANG_UITGESLOTEN("drugsopvang uitgesloten"),
    @XmlEnumValue("ecologische verbindingszone uitgesloten")
    ECOLOGISCHE_VERBINDINGSZONE_UITGESLOTEN("ecologische verbindingszone uitgesloten"),
    @XmlEnumValue("ecologische waarde uitgesloten")
    ECOLOGISCHE_WAARDE_UITGESLOTEN("ecologische waarde uitgesloten"),
    @XmlEnumValue("eendenkooi uitgesloten")
    EENDENKOOI_UITGESLOTEN("eendenkooi uitgesloten"),
    @XmlEnumValue("erf uitgesloten")
    ERF_UITGESLOTEN("erf uitgesloten"),
    @XmlEnumValue("evenemententerrein uitgesloten")
    EVENEMENTENTERREIN_UITGESLOTEN("evenemententerrein uitgesloten"),
    @XmlEnumValue("feestzaal uitgesloten")
    FEESTZAAL_UITGESLOTEN("feestzaal uitgesloten"),
    @XmlEnumValue("fruitteelt uitgesloten")
    FRUITTEELT_UITGESLOTEN("fruitteelt uitgesloten"),
    @XmlEnumValue("garage uitgesloten")
    GARAGE_UITGESLOTEN("garage uitgesloten"),
    @XmlEnumValue("geluidscherm uitgesloten")
    GELUIDSCHERM_UITGESLOTEN("geluidscherm uitgesloten"),
    @XmlEnumValue("geluidwal uitgesloten")
    GELUIDWAL_UITGESLOTEN("geluidwal uitgesloten"),
    @XmlEnumValue("gemaal uitgesloten")
    GEMAAL_UITGESLOTEN("gemaal uitgesloten"),
    @XmlEnumValue("gemengd uitgesloten")
    GEMENGD_UITGESLOTEN("gemengd uitgesloten"),
    @XmlEnumValue("geomorfologische waarde uitgesloten")
    GEOMORFOLOGISCHE_WAARDE_UITGESLOTEN("geomorfologische waarde uitgesloten"),
    @XmlEnumValue("gezondheidszorg uitgesloten")
    GEZONDHEIDSZORG_UITGESLOTEN("gezondheidszorg uitgesloten"),
    @XmlEnumValue("glastuinbouw uitgesloten")
    GLASTUINBOUW_UITGESLOTEN("glastuinbouw uitgesloten"),
    @XmlEnumValue("golfbaan uitgesloten")
    GOLFBAAN_UITGESLOTEN("golfbaan uitgesloten"),
    @XmlEnumValue("groen uitgesloten")
    GROEN_UITGESLOTEN("groen uitgesloten"),
    @XmlEnumValue("gronddepot uitgesloten")
    GRONDDEPOT_UITGESLOTEN("gronddepot uitgesloten"),
    @XmlEnumValue("grondgebonden veehouderij uitgesloten")
    GRONDGEBONDEN_VEEHOUDERIJ_UITGESLOTEN("grondgebonden veehouderij uitgesloten"),
    @XmlEnumValue("groothandel uitgesloten")
    GROOTHANDEL_UITGESLOTEN("groothandel uitgesloten"),
    @XmlEnumValue("haven uitgesloten")
    HAVEN_UITGESLOTEN("haven uitgesloten"),
    @XmlEnumValue("horeca uitgesloten")
    HORECA_UITGESLOTEN("horeca uitgesloten"),
    @XmlEnumValue("houtsingel uitgesloten")
    HOUTSINGEL_UITGESLOTEN("houtsingel uitgesloten"),
    @XmlEnumValue("houtwal uitgesloten")
    HOUTWAL_UITGESLOTEN("houtwal uitgesloten"),
    @XmlEnumValue("hovenier uitgesloten")
    HOVENIER_UITGESLOTEN("hovenier uitgesloten"),
    @XmlEnumValue("ijsbaan uitgesloten")
    IJSBAAN_UITGESLOTEN("ijsbaan uitgesloten"),
    @XmlEnumValue("infrastructuur uitgesloten")
    INFRASTRUCTUUR_UITGESLOTEN("infrastructuur uitgesloten"),
    @XmlEnumValue("intensieve kwekerij uitgesloten")
    INTENSIEVE_KWEKERIJ_UITGESLOTEN("intensieve kwekerij uitgesloten"),
    @XmlEnumValue("intensieve veehouderij uitgesloten")
    INTENSIEVE_VEEHOUDERIJ_UITGESLOTEN("intensieve veehouderij uitgesloten"),
    @XmlEnumValue("internetcaf\u00e9 uitgesloten")
    INTERNETCAFÉ_UITGESLOTEN("internetcaf\u00e9 uitgesloten"),
    @XmlEnumValue("internetwinkel uitgesloten")
    INTERNETWINKEL_UITGESLOTEN("internetwinkel uitgesloten"),
    @XmlEnumValue("jachthaven uitgesloten")
    JACHTHAVEN_UITGESLOTEN("jachthaven uitgesloten"),
    @XmlEnumValue("jeugdopvang uitgesloten")
    JEUGDOPVANG_UITGESLOTEN("jeugdopvang uitgesloten"),
    @XmlEnumValue("jongeren ontmoetingsplek uitgesloten")
    JONGEREN_ONTMOETINGSPLEK_UITGESLOTEN("jongeren ontmoetingsplek uitgesloten"),
    @XmlEnumValue("justiti\u00eble inrichting uitgesloten")
    JUSTITIËLE_INRICHTING_UITGESLOTEN("justiti\u00eble inrichting uitgesloten"),
    @XmlEnumValue("kamerverhuur uitgesloten")
    KAMERVERHUUR_UITGESLOTEN("kamerverhuur uitgesloten"),
    @XmlEnumValue("kampeerboerderij uitgesloten")
    KAMPEERBOERDERIJ_UITGESLOTEN("kampeerboerderij uitgesloten"),
    @XmlEnumValue("kampeerterrein uitgesloten")
    KAMPEERTERREIN_UITGESLOTEN("kampeerterrein uitgesloten"),
    @XmlEnumValue("kantoor uitgesloten")
    KANTOOR_UITGESLOTEN("kantoor uitgesloten"),
    @XmlEnumValue("kartbaan uitgesloten")
    KARTBAAN_UITGESLOTEN("kartbaan uitgesloten"),
    @XmlEnumValue("kas uitgesloten")
    KAS_UITGESLOTEN("kas uitgesloten"),
    @XmlEnumValue("kazerne uitgesloten")
    KAZERNE_UITGESLOTEN("kazerne uitgesloten"),
    @XmlEnumValue("kinderboerderij uitgesloten")
    KINDERBOERDERIJ_UITGESLOTEN("kinderboerderij uitgesloten"),
    @XmlEnumValue("kunstijsbaan uitgesloten")
    KUNSTIJSBAAN_UITGESLOTEN("kunstijsbaan uitgesloten"),
    @XmlEnumValue("laad- en losplaats uitgesloten")
    LAAD_EN_LOSPLAATS_UITGESLOTEN("laad- en losplaats uitgesloten"),
    @XmlEnumValue("landingsbaan uitgesloten")
    LANDINGSBAAN_UITGESLOTEN("landingsbaan uitgesloten"),
    @XmlEnumValue("landschapswaarden uitgesloten")
    LANDSCHAPSWAARDEN_UITGESLOTEN("landschapswaarden uitgesloten"),
    @XmlEnumValue("leidingstrook uitgesloten")
    LEIDINGSTROOK_UITGESLOTEN("leidingstrook uitgesloten"),
    @XmlEnumValue("ligplaats uitgesloten")
    LIGPLAATS_UITGESLOTEN("ligplaats uitgesloten"),
    @XmlEnumValue("luchthaven uitgesloten")
    LUCHTHAVEN_UITGESLOTEN("luchthaven uitgesloten"),
    @XmlEnumValue("luchtverkeer uitgesloten")
    LUCHTVERKEER_UITGESLOTEN("luchtverkeer uitgesloten"),
    @XmlEnumValue("maatschappelijk uitgesloten")
    MAATSCHAPPELIJK_UITGESLOTEN("maatschappelijk uitgesloten"),
    @XmlEnumValue("manege uitgesloten")
    MANEGE_UITGESLOTEN("manege uitgesloten"),
    @XmlEnumValue("markt uitgesloten")
    MARKT_UITGESLOTEN("markt uitgesloten"),
    @XmlEnumValue("meer uitgesloten")
    MEER_UITGESLOTEN("meer uitgesloten"),
    @XmlEnumValue("militaire zaken uitgesloten")
    MILITAIRE_ZAKEN_UITGESLOTEN("militaire zaken uitgesloten"),
    @XmlEnumValue("militair oefenterrein uitgesloten")
    MILITAIR_OEFENTERREIN_UITGESLOTEN("militair oefenterrein uitgesloten"),
    @XmlEnumValue("modelvliegtuigbaan uitgesloten")
    MODELVLIEGTUIGBAAN_UITGESLOTEN("modelvliegtuigbaan uitgesloten"),
    @XmlEnumValue("monumentale boom uitgesloten")
    MONUMENTALE_BOOM_UITGESLOTEN("monumentale boom uitgesloten"),
    @XmlEnumValue("motorcrossterrein uitgesloten")
    MOTORCROSSTERREIN_UITGESLOTEN("motorcrossterrein uitgesloten"),
    @XmlEnumValue("munitiedepot uitgesloten")
    MUNITIEDEPOT_UITGESLOTEN("munitiedepot uitgesloten"),
    @XmlEnumValue("museum uitgesloten")
    MUSEUM_UITGESLOTEN("museum uitgesloten"),
    @XmlEnumValue("muziekschool uitgesloten")
    MUZIEKSCHOOL_UITGESLOTEN("muziekschool uitgesloten"),
    @XmlEnumValue("muziektheater uitgesloten")
    MUZIEKTHEATER_UITGESLOTEN("muziektheater uitgesloten"),
    @XmlEnumValue("naschoolse opvang uitgesloten")
    NASCHOOLSE_OPVANG_UITGESLOTEN("naschoolse opvang uitgesloten"),
    @XmlEnumValue("natuur- en landschapswaarden uitgesloten")
    NATUUR_EN_LANDSCHAPSWAARDEN_UITGESLOTEN("natuur- en landschapswaarden uitgesloten"),
    @XmlEnumValue("natuur uitgesloten")
    NATUUR_UITGESLOTEN("natuur uitgesloten"),
    @XmlEnumValue("natuurwaarden uitgesloten")
    NATUURWAARDEN_UITGESLOTEN("natuurwaarden uitgesloten"),
    @XmlEnumValue("nutsbedrijf uitgesloten")
    NUTSBEDRIJF_UITGESLOTEN("nutsbedrijf uitgesloten"),
    @XmlEnumValue("nutsvoorziening uitgesloten")
    NUTSVOORZIENING_UITGESLOTEN("nutsvoorziening uitgesloten"),
    @XmlEnumValue("oever uitgesloten")
    OEVER_UITGESLOTEN("oever uitgesloten"),
    @XmlEnumValue("onderwijs uitgesloten")
    ONDERWIJS_UITGESLOTEN("onderwijs uitgesloten"),
    @XmlEnumValue("ontsluiting uitgesloten")
    ONTSLUITING_UITGESLOTEN("ontsluiting uitgesloten"),
    @XmlEnumValue("openbaar vervoer uitgesloten")
    OPENBAAR_VERVOER_UITGESLOTEN("openbaar vervoer uitgesloten"),
    @XmlEnumValue("openbare dienstverlening uitgesloten")
    OPENBARE_DIENSTVERLENING_UITGESLOTEN("openbare dienstverlening uitgesloten"),
    @XmlEnumValue("opslag uitgesloten")
    OPSLAG_UITGESLOTEN("opslag uitgesloten"),
    @XmlEnumValue("openbaar vervoerstation uitgesloten")
    OPENBAAR_VERVOERSTATION_UITGESLOTEN("openbaar vervoerstation uitgesloten"),
    @XmlEnumValue("paardenfokkerij uitgesloten")
    PAARDENFOKKERIJ_UITGESLOTEN("paardenfokkerij uitgesloten"),
    @XmlEnumValue("paardenhouderij uitgesloten")
    PAARDENHOUDERIJ_UITGESLOTEN("paardenhouderij uitgesloten"),
    @XmlEnumValue("pad uitgesloten")
    PAD_UITGESLOTEN("pad uitgesloten"),
    @XmlEnumValue("park uitgesloten")
    PARK_UITGESLOTEN("park uitgesloten"),
    @XmlEnumValue("parkeergarage uitgesloten")
    PARKEERGARAGE_UITGESLOTEN("parkeergarage uitgesloten"),
    @XmlEnumValue("parkeerterrein uitgesloten")
    PARKEERTERREIN_UITGESLOTEN("parkeerterrein uitgesloten"),
    @XmlEnumValue("partyboerderij uitgesloten")
    PARTYBOERDERIJ_UITGESLOTEN("partyboerderij uitgesloten"),
    @XmlEnumValue("passantenhaven uitgesloten")
    PASSANTENHAVEN_UITGESLOTEN("passantenhaven uitgesloten"),
    @XmlEnumValue("pitch & putt uitgesloten")
    PITCH_PUTT_UITGESLOTEN("pitch & putt uitgesloten"),
    @XmlEnumValue("plantsoen uitgesloten")
    PLANTSOEN_UITGESLOTEN("plantsoen uitgesloten"),
    @XmlEnumValue("plein uitgesloten")
    PLEIN_UITGESLOTEN("plein uitgesloten"),
    @XmlEnumValue("praktijkruimte uitgesloten")
    PRAKTIJKRUIMTE_UITGESLOTEN("praktijkruimte uitgesloten"),
    @XmlEnumValue("prostitutie uitgesloten")
    PROSTITUTIE_UITGESLOTEN("prostitutie uitgesloten"),
    @XmlEnumValue("raamprostitutie (raamexploitatie) uitgesloten")
    RAAMPROSTITUTIE_RAAMEXPLOITATIE_UITGESLOTEN("raamprostitutie (raamexploitatie) uitgesloten"),
    @XmlEnumValue("railverkeer uitgesloten")
    RAILVERKEER_UITGESLOTEN("railverkeer uitgesloten"),
    @XmlEnumValue("recreatie uitgesloten")
    RECREATIE_UITGESLOTEN("recreatie uitgesloten"),
    @XmlEnumValue("recreatiewoning uitgesloten")
    RECREATIEWONING_UITGESLOTEN("recreatiewoning uitgesloten"),
    @XmlEnumValue("religie uitgesloten")
    RELIGIE_UITGESLOTEN("religie uitgesloten"),
    @XmlEnumValue("risicovolle inrichting uitgesloten")
    RISICOVOLLE_INRICHTING_UITGESLOTEN("risicovolle inrichting uitgesloten"),
    @XmlEnumValue("rivier uitgesloten")
    RIVIER_UITGESLOTEN("rivier uitgesloten"),
    @XmlEnumValue("sauna uitgesloten")
    SAUNA_UITGESLOTEN("sauna uitgesloten"),
    @XmlEnumValue("schiphuis uitgesloten")
    SCHIPHUIS_UITGESLOTEN("schiphuis uitgesloten"),
    @XmlEnumValue("seksinrichting uitgesloten")
    SEKSINRICHTING_UITGESLOTEN("seksinrichting uitgesloten"),
    @XmlEnumValue("sierteelt uitgesloten")
    SIERTEELT_UITGESLOTEN("sierteelt uitgesloten"),
    @XmlEnumValue("silo uitgesloten")
    SILO_UITGESLOTEN("silo uitgesloten"),
    @XmlEnumValue("skeelerbaan uitgesloten")
    SKEELERBAAN_UITGESLOTEN("skeelerbaan uitgesloten"),
    @XmlEnumValue("skibaan uitgesloten")
    SKIBAAN_UITGESLOTEN("skibaan uitgesloten"),
    @XmlEnumValue("sluis uitgesloten")
    SLUIS_UITGESLOTEN("sluis uitgesloten"),
    @XmlEnumValue("speeltuin uitgesloten")
    SPEELTUIN_UITGESLOTEN("speeltuin uitgesloten"),
    @XmlEnumValue("speelvoorziening uitgesloten")
    SPEELVOORZIENING_UITGESLOTEN("speelvoorziening uitgesloten"),
    @XmlEnumValue("spoorweg uitgesloten")
    SPOORWEG_UITGESLOTEN("spoorweg uitgesloten"),
    @XmlEnumValue("sport uitgesloten")
    SPORT_UITGESLOTEN("sport uitgesloten"),
    @XmlEnumValue("sportcentrum uitgesloten")
    SPORTCENTRUM_UITGESLOTEN("sportcentrum uitgesloten"),
    @XmlEnumValue("sporthal uitgesloten")
    SPORTHAL_UITGESLOTEN("sporthal uitgesloten"),
    @XmlEnumValue("sportveld uitgesloten")
    SPORTVELD_UITGESLOTEN("sportveld uitgesloten"),
    @XmlEnumValue("sportzaal uitgesloten")
    SPORTZAAL_UITGESLOTEN("sportzaal uitgesloten"),
    @XmlEnumValue("squashcentrum uitgesloten")
    SQUASHCENTRUM_UITGESLOTEN("squashcentrum uitgesloten"),
    @XmlEnumValue("stadion uitgesloten")
    STADION_UITGESLOTEN("stadion uitgesloten"),
    @XmlEnumValue("steiger uitgesloten")
    STEIGER_UITGESLOTEN("steiger uitgesloten"),
    @XmlEnumValue("strand uitgesloten")
    STRAND_UITGESLOTEN("strand uitgesloten"),
    @XmlEnumValue("strandhuis uitgesloten")
    STRANDHUIS_UITGESLOTEN("strandhuis uitgesloten"),
    @XmlEnumValue("studentenhuisvesting uitgesloten")
    STUDENTENHUISVESTING_UITGESLOTEN("studentenhuisvesting uitgesloten"),
    @XmlEnumValue("stuw uitgesloten")
    STUW_UITGESLOTEN("stuw uitgesloten"),
    @XmlEnumValue("supermarkt uitgesloten")
    SUPERMARKT_UITGESLOTEN("supermarkt uitgesloten"),
    @XmlEnumValue("tennisbaan uitgesloten")
    TENNISBAAN_UITGESLOTEN("tennisbaan uitgesloten"),
    @XmlEnumValue("terras uitgesloten")
    TERRAS_UITGESLOTEN("terras uitgesloten"),
    @XmlEnumValue("theater uitgesloten")
    THEATER_UITGESLOTEN("theater uitgesloten"),
    @XmlEnumValue("tuin uitgesloten")
    TUIN_UITGESLOTEN("tuin uitgesloten"),
    @XmlEnumValue("tuinbouw uitgesloten")
    TUINBOUW_UITGESLOTEN("tuinbouw uitgesloten"),
    @XmlEnumValue("tuincentrum uitgesloten")
    TUINCENTRUM_UITGESLOTEN("tuincentrum uitgesloten"),
    @XmlEnumValue("tunnel uitgesloten")
    TUNNEL_UITGESLOTEN("tunnel uitgesloten"),
    @XmlEnumValue("uitvaartcentrum uitgesloten")
    UITVAARTCENTRUM_UITGESLOTEN("uitvaartcentrum uitgesloten"),
    @XmlEnumValue("vaarweg uitgesloten")
    VAARWEG_UITGESLOTEN("vaarweg uitgesloten"),
    @XmlEnumValue("veerhaven uitgesloten")
    VEERHAVEN_UITGESLOTEN("veerhaven uitgesloten"),
    @XmlEnumValue("ven uitgesloten")
    VEN_UITGESLOTEN("ven uitgesloten"),
    @XmlEnumValue("verblijfsgebied uitgesloten")
    VERBLIJFSGEBIED_UITGESLOTEN("verblijfsgebied uitgesloten"),
    @XmlEnumValue("verblijfsrecreatie uitgesloten")
    VERBLIJFSRECREATIE_UITGESLOTEN("verblijfsrecreatie uitgesloten"),
    @XmlEnumValue("verenigingsleven uitgesloten")
    VERENIGINGSLEVEN_UITGESLOTEN("verenigingsleven uitgesloten"),
    @XmlEnumValue("verkeer uitgesloten")
    VERKEER_UITGESLOTEN("verkeer uitgesloten"),
    @XmlEnumValue("verkoop eigen producten uitgesloten")
    VERKOOP_EIGEN_PRODUCTEN_UITGESLOTEN("verkoop eigen producten uitgesloten"),
    @XmlEnumValue("verkooppunt motorbrandstoffen met lpg uitgesloten")
    VERKOOPPUNT_MOTORBRANDSTOFFEN_MET_LPG_UITGESLOTEN("verkooppunt motorbrandstoffen met lpg uitgesloten"),
    @XmlEnumValue("verkooppunt motorbrandstoffen zonder lpg uitgesloten")
    VERKOOPPUNT_MOTORBRANDSTOFFEN_ZONDER_LPG_UITGESLOTEN("verkooppunt motorbrandstoffen zonder lpg uitgesloten"),
    @XmlEnumValue("vertrek- en aankomsthal uitgesloten")
    VERTREK_EN_AANKOMSTHAL_UITGESLOTEN("vertrek- en aankomsthal uitgesloten"),
    @XmlEnumValue("vijver uitgesloten")
    VIJVER_UITGESLOTEN("vijver uitgesloten"),
    @XmlEnumValue("viskwekerij uitgesloten")
    VISKWEKERIJ_UITGESLOTEN("viskwekerij uitgesloten"),
    @XmlEnumValue("volkstuin uitgesloten")
    VOLKSTUIN_UITGESLOTEN("volkstuin uitgesloten"),
    @XmlEnumValue("vulpunt lpg uitgesloten")
    VULPUNT_LPG_UITGESLOTEN("vulpunt lpg uitgesloten"),
    @XmlEnumValue("waardevolle boom uitgesloten")
    WAARDEVOLLE_BOOM_UITGESLOTEN("waardevolle boom uitgesloten"),
    @XmlEnumValue("water uitgesloten")
    WATER_UITGESLOTEN("water uitgesloten"),
    @XmlEnumValue("waterberging uitgesloten")
    WATERBERGING_UITGESLOTEN("waterberging uitgesloten"),
    @XmlEnumValue("waterkering uitgesloten")
    WATERKERING_UITGESLOTEN("waterkering uitgesloten"),
    @XmlEnumValue("waterstaat uitgesloten")
    WATERSTAAT_UITGESLOTEN("waterstaat uitgesloten"),
    @XmlEnumValue("waterweg uitgesloten")
    WATERWEG_UITGESLOTEN("waterweg uitgesloten"),
    @XmlEnumValue("waterzuiveringsinstallatie uitgesloten")
    WATERZUIVERINGSINSTALLATIE_UITGESLOTEN("waterzuiveringsinstallatie uitgesloten"),
    @XmlEnumValue("weg uitgesloten")
    WEG_UITGESLOTEN("weg uitgesloten"),
    @XmlEnumValue("wellness uitgesloten")
    WELLNESS_UITGESLOTEN("wellness uitgesloten"),
    @XmlEnumValue("welzijnsinstelling uitgesloten")
    WELZIJNSINSTELLING_UITGESLOTEN("welzijnsinstelling uitgesloten"),
    @XmlEnumValue("wielerbaan uitgesloten")
    WIELERBAAN_UITGESLOTEN("wielerbaan uitgesloten"),
    @XmlEnumValue("windturbine uitgesloten")
    WINDTURBINE_UITGESLOTEN("windturbine uitgesloten"),
    @XmlEnumValue("windturbinepark uitgesloten")
    WINDTURBINEPARK_UITGESLOTEN("windturbinepark uitgesloten"),
    @XmlEnumValue("wonen uitgesloten")
    WONEN_UITGESLOTEN("wonen uitgesloten"),
    @XmlEnumValue("woongebied uitgesloten")
    WOONGEBIED_UITGESLOTEN("woongebied uitgesloten"),
    @XmlEnumValue("woonschepenligplaats uitgesloten")
    WOONSCHEPENLIGPLAATS_UITGESLOTEN("woonschepenligplaats uitgesloten"),
    @XmlEnumValue("woonwagenstandplaats uitgesloten")
    WOONWAGENSTANDPLAATS_UITGESLOTEN("woonwagenstandplaats uitgesloten"),
    @XmlEnumValue("zee uitgesloten")
    ZEE_UITGESLOTEN("zee uitgesloten"),
    @XmlEnumValue("zend-/ontvangstinstallatie uitgesloten")
    ZEND_ONTVANGSTINSTALLATIE_UITGESLOTEN("zend-/ontvangstinstallatie uitgesloten"),
    @XmlEnumValue("zorginstelling uitgesloten")
    ZORGINSTELLING_UITGESLOTEN("zorginstelling uitgesloten"),
    @XmlEnumValue("zorgboerderij uitgesloten")
    ZORGBOERDERIJ_UITGESLOTEN("zorgboerderij uitgesloten"),
    @XmlEnumValue("zorgwoning uitgesloten")
    ZORGWONING_UITGESLOTEN("zorgwoning uitgesloten"),
    @XmlEnumValue("zwembad uitgesloten")
    ZWEMBAD_UITGESLOTEN("zwembad uitgesloten");
    private final String value;

    FunctieaanduidingenEnumerationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctieaanduidingenEnumerationType fromValue(String v) {
        for (FunctieaanduidingenEnumerationType c: FunctieaanduidingenEnumerationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
