//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.29 at 03:18:07 PM CEST 
//


package nl.b3p.imro._2008._11;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.b3p.imro.gml4nl.AbstractFeatureType;


/**
 * <p>Java class for MetadataIMRObestandType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MetadataIMRObestandType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="datasetTitel" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="creatiedatum" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="bronbeheerder" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="codeerVerantwoordelijke" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="naamApplicatieschema" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="codeReferentiesysteem" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="toepassingsschaal" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="applicatieIdentificatie" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *         &lt;element name="versieXMLschema" type="{http://www.geonovum.nl/imro/2008/1}NotEmptyString"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadataIMRObestandType", propOrder = {
    "datasetTitel",
    "creatiedatum",
    "bronbeheerder",
    "codeerVerantwoordelijke",
    "naamApplicatieschema",
    "codeReferentiesysteem",
    "toepassingsschaal",
    "applicatieIdentificatie",
    "versieXMLschema"
})
public class MetadataIMRObestandType
    extends AbstractFeatureType
{

    @XmlElement(required = true)
    protected String datasetTitel;
    @XmlElement(required = true)
    protected String creatiedatum;
    @XmlElement(required = true)
    protected String bronbeheerder;
    @XmlElement(required = true)
    protected String codeerVerantwoordelijke;
    @XmlElement(required = true)
    protected String naamApplicatieschema;
    @XmlElement(required = true)
    protected String codeReferentiesysteem;
    @XmlElement(required = true)
    protected BigInteger toepassingsschaal;
    @XmlElement(required = true)
    protected String applicatieIdentificatie;
    @XmlElement(required = true)
    protected String versieXMLschema;

    /**
     * Gets the value of the datasetTitel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetTitel() {
        return datasetTitel;
    }

    /**
     * Sets the value of the datasetTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetTitel(String value) {
        this.datasetTitel = value;
    }

    /**
     * Gets the value of the creatiedatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatiedatum() {
        return creatiedatum;
    }

    /**
     * Sets the value of the creatiedatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatiedatum(String value) {
        this.creatiedatum = value;
    }

    /**
     * Gets the value of the bronbeheerder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBronbeheerder() {
        return bronbeheerder;
    }

    /**
     * Sets the value of the bronbeheerder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBronbeheerder(String value) {
        this.bronbeheerder = value;
    }

    /**
     * Gets the value of the codeerVerantwoordelijke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeerVerantwoordelijke() {
        return codeerVerantwoordelijke;
    }

    /**
     * Sets the value of the codeerVerantwoordelijke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeerVerantwoordelijke(String value) {
        this.codeerVerantwoordelijke = value;
    }

    /**
     * Gets the value of the naamApplicatieschema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaamApplicatieschema() {
        return naamApplicatieschema;
    }

    /**
     * Sets the value of the naamApplicatieschema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaamApplicatieschema(String value) {
        this.naamApplicatieschema = value;
    }

    /**
     * Gets the value of the codeReferentiesysteem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeReferentiesysteem() {
        return codeReferentiesysteem;
    }

    /**
     * Sets the value of the codeReferentiesysteem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeReferentiesysteem(String value) {
        this.codeReferentiesysteem = value;
    }

    /**
     * Gets the value of the toepassingsschaal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getToepassingsschaal() {
        return toepassingsschaal;
    }

    /**
     * Sets the value of the toepassingsschaal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setToepassingsschaal(BigInteger value) {
        this.toepassingsschaal = value;
    }

    /**
     * Gets the value of the applicatieIdentificatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicatieIdentificatie() {
        return applicatieIdentificatie;
    }

    /**
     * Sets the value of the applicatieIdentificatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicatieIdentificatie(String value) {
        this.applicatieIdentificatie = value;
    }

    /**
     * Gets the value of the versieXMLschema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersieXMLschema() {
        return versieXMLschema;
    }

    /**
     * Sets the value of the versieXMLschema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersieXMLschema(String value) {
        this.versieXMLschema = value;
    }

}
