version: '{build}-({branch})'

skip_tags: true
clone_folder: C:\projects\imro-harvester
clone_depth: 20

environment:
  fast_finish: true

  matrix:
  - JDK: JDK8
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

init:
  - cd c:\
  - wget http://cert.pkioverheid.nl/RootCA-G2.cer
  - keytool -importcert -file RootCA-G2.cer -alias "Staat der Nederlanden Root CA G2" -keystore C:\Program Files\Java\jdk1.8.0\jre\lib\security\cacerts -storepass:changeit
  
install:
  - cmd: echo %PATH%
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  #- ps: .\.appveyor\set-maven-proxy.ps1
  - mvn install -U -DskipTests -B -V -fae -q
  
  
cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml

build: off

test_script:
  - mvn -e test -B
