//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 11:13:35 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geonovum.nl/stri/2006/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.b3p.stri._2006._12b;
