//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 09:54:50 AM CET 
//


package nl.geonovum.imro._2012._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaardeEnTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaardeEnTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="waarde" type="{http://www.geonovum.nl/imro/2012/1.1}NotEmptyString"/>
 *         &lt;element name="waardeType" type="{http://www.geonovum.nl/imro/2012/1.1}OmvangWaardeType"/>
 *         &lt;element name="symboolCode" type="{http://www.geonovum.nl/imro/2012/1.1}SymboolCodeMatrixType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaardeEnTypeType", propOrder = {
    "waarde",
    "waardeType",
    "symboolCode"
})
public class WaardeEnTypeType {

    @XmlElement(required = true)
    protected String waarde;
    @XmlElement(required = true)
    protected String waardeType;
    protected String symboolCode;

    /**
     * Gets the value of the waarde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaarde() {
        return waarde;
    }

    /**
     * Sets the value of the waarde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaarde(String value) {
        this.waarde = value;
    }

    /**
     * Gets the value of the waardeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaardeType() {
        return waardeType;
    }

    /**
     * Sets the value of the waardeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaardeType(String value) {
        this.waardeType = value;
    }

    /**
     * Gets the value of the symboolCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymboolCode() {
        return symboolCode;
    }

    /**
     * Sets the value of the symboolCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymboolCode(String value) {
        this.symboolCode = value;
    }

}
