//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:50:32 PM CET 
//


package nl.b3p.imro.stri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Eigenschappen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Naam" type="{http://www.geonovum.nl/stri/2012/2.0}Naam"/>
 *                   &lt;element name="Type" type="{http://www.geonovum.nl/stri/2012/2.0}TypePlan"/>
 *                   &lt;element name="Status" type="{http://www.geonovum.nl/stri/2012/2.0}PlanStatus"/>
 *                   &lt;element name="Datum" type="{http://www.geonovum.nl/stri/2012/2.0}Datum"/>
 *                   &lt;element name="VersieGML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VersiePraktijkRichtlijn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Onderdelen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GML" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel"/>
 *                   &lt;element name="PlanTeksten" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
 *                   &lt;element name="Regels" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
 *                   &lt;element name="BeleidsOfBesluitDocument" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
 *                   &lt;element name="Toelichting" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
 *                   &lt;element name="VaststellingsBesluit" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
 *                   &lt;element name="Bijlage" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Illustratie" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="GeleideFormulier" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BasisURL" type="{http://www.geonovum.nl/stri/2012/2.0}PlanBasisURL" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Supplementen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StartPagina" type="{http://www.geonovum.nl/stri/2012/2.0}PlanSupplement" minOccurs="0"/>
 *                   &lt;element name="CSS" type="{http://www.geonovum.nl/stri/2012/2.0}PlanSupplement" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BasisURL" type="{http://www.geonovum.nl/stri/2012/2.0}PlanBasisURL" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="Id" use="required" type="{http://www.geonovum.nl/stri/2012/2.0}PlanID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Plan", namespace = "http://www.geonovum.nl/stri/2012/2.0")
public class Plan {

    @XmlElement(name = "Eigenschappen", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
    protected Plan.Eigenschappen eigenschappen;
    @XmlElement(name = "Onderdelen", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
    protected Plan.Onderdelen onderdelen;
    @XmlElement(name = "Supplementen", namespace = "http://www.geonovum.nl/stri/2012/2.0")
    protected Plan.Supplementen supplementen;
    @XmlAttribute(name = "Id", required = true)
    protected String id;

    /**
     * Gets the value of the eigenschappen property.
     * 
     * @return
     *     possible object is
     *     {@link Plan.Eigenschappen }
     *     
     */
    public Plan.Eigenschappen getEigenschappen() {
        return eigenschappen;
    }

    /**
     * Sets the value of the eigenschappen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan.Eigenschappen }
     *     
     */
    public void setEigenschappen(Plan.Eigenschappen value) {
        this.eigenschappen = value;
    }

    /**
     * Gets the value of the onderdelen property.
     * 
     * @return
     *     possible object is
     *     {@link Plan.Onderdelen }
     *     
     */
    public Plan.Onderdelen getOnderdelen() {
        return onderdelen;
    }

    /**
     * Sets the value of the onderdelen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan.Onderdelen }
     *     
     */
    public void setOnderdelen(Plan.Onderdelen value) {
        this.onderdelen = value;
    }

    /**
     * Gets the value of the supplementen property.
     * 
     * @return
     *     possible object is
     *     {@link Plan.Supplementen }
     *     
     */
    public Plan.Supplementen getSupplementen() {
        return supplementen;
    }

    /**
     * Sets the value of the supplementen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan.Supplementen }
     *     
     */
    public void setSupplementen(Plan.Supplementen value) {
        this.supplementen = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Naam" type="{http://www.geonovum.nl/stri/2012/2.0}Naam"/>
     *         &lt;element name="Type" type="{http://www.geonovum.nl/stri/2012/2.0}TypePlan"/>
     *         &lt;element name="Status" type="{http://www.geonovum.nl/stri/2012/2.0}PlanStatus"/>
     *         &lt;element name="Datum" type="{http://www.geonovum.nl/stri/2012/2.0}Datum"/>
     *         &lt;element name="VersieGML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VersiePraktijkRichtlijn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Eigenschappen {

        @XmlElement(name = "Naam", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        protected String naam;
        @XmlElement(name = "Type", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        @XmlSchemaType(name = "string")
        protected TypePlan type;
        @XmlElement(name = "Status", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        @XmlSchemaType(name = "string")
        protected PlanStatus status;
        @XmlElement(name = "Datum", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;
        @XmlElement(name = "VersieGML", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        protected String versieGML;
        @XmlElement(name = "VersiePraktijkRichtlijn", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        protected String versiePraktijkRichtlijn;

        /**
         * Gets the value of the naam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaam() {
            return naam;
        }

        /**
         * Sets the value of the naam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaam(String value) {
            this.naam = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link TypePlan }
         *     
         */
        public TypePlan getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypePlan }
         *     
         */
        public void setType(TypePlan value) {
            this.type = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link PlanStatus }
         *     
         */
        public PlanStatus getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link PlanStatus }
         *     
         */
        public void setStatus(PlanStatus value) {
            this.status = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the versieGML property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersieGML() {
            return versieGML;
        }

        /**
         * Sets the value of the versieGML property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersieGML(String value) {
            this.versieGML = value;
        }

        /**
         * Gets the value of the versiePraktijkRichtlijn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersiePraktijkRichtlijn() {
            return versiePraktijkRichtlijn;
        }

        /**
         * Sets the value of the versiePraktijkRichtlijn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersiePraktijkRichtlijn(String value) {
            this.versiePraktijkRichtlijn = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GML" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel"/>
     *         &lt;element name="PlanTeksten" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
     *         &lt;element name="Regels" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
     *         &lt;element name="BeleidsOfBesluitDocument" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
     *         &lt;element name="Toelichting" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
     *         &lt;element name="VaststellingsBesluit" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" minOccurs="0"/>
     *         &lt;element name="Bijlage" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Illustratie" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="GeleideFormulier" type="{http://www.geonovum.nl/stri/2012/2.0}PlanOnderdeel"/>
     *       &lt;/sequence>
     *       &lt;attribute name="BasisURL" type="{http://www.geonovum.nl/stri/2012/2.0}PlanBasisURL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gml",
        "planTeksten",
        "regels",
        "beleidsOfBesluitDocument",
        "toelichting",
        "vaststellingsBesluit",
        "bijlage",
        "illustratie",
        "geleideFormulier"
    })
    public static class Onderdelen {

        @XmlElement(name = "GML", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String gml;
        @XmlElement(name = "PlanTeksten", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String planTeksten;
        @XmlElement(name = "Regels", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String regels;
        @XmlElement(name = "BeleidsOfBesluitDocument", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String beleidsOfBesluitDocument;
        @XmlElement(name = "Toelichting", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String toelichting;
        @XmlElement(name = "VaststellingsBesluit", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String vaststellingsBesluit;
        @XmlElement(name = "Bijlage", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected List<String> bijlage;
        @XmlElement(name = "Illustratie", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected List<String> illustratie;
        @XmlElement(name = "GeleideFormulier", namespace = "http://www.geonovum.nl/stri/2012/2.0", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String geleideFormulier;
        @XmlAttribute(name = "BasisURL")
        protected String basisURL;

        /**
         * Gets the value of the gml property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGML() {
            return gml;
        }

        /**
         * Sets the value of the gml property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGML(String value) {
            this.gml = value;
        }

        /**
         * Gets the value of the planTeksten property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanTeksten() {
            return planTeksten;
        }

        /**
         * Sets the value of the planTeksten property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanTeksten(String value) {
            this.planTeksten = value;
        }

        /**
         * Gets the value of the regels property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegels() {
            return regels;
        }

        /**
         * Sets the value of the regels property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegels(String value) {
            this.regels = value;
        }

        /**
         * Gets the value of the beleidsOfBesluitDocument property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeleidsOfBesluitDocument() {
            return beleidsOfBesluitDocument;
        }

        /**
         * Sets the value of the beleidsOfBesluitDocument property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeleidsOfBesluitDocument(String value) {
            this.beleidsOfBesluitDocument = value;
        }

        /**
         * Gets the value of the toelichting property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToelichting() {
            return toelichting;
        }

        /**
         * Sets the value of the toelichting property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToelichting(String value) {
            this.toelichting = value;
        }

        /**
         * Gets the value of the vaststellingsBesluit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVaststellingsBesluit() {
            return vaststellingsBesluit;
        }

        /**
         * Sets the value of the vaststellingsBesluit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVaststellingsBesluit(String value) {
            this.vaststellingsBesluit = value;
        }

        /**
         * Gets the value of the bijlage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bijlage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBijlage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBijlage() {
            if (bijlage == null) {
                bijlage = new ArrayList<String>();
            }
            return this.bijlage;
        }

        /**
         * Gets the value of the illustratie property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the illustratie property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIllustratie().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getIllustratie() {
            if (illustratie == null) {
                illustratie = new ArrayList<String>();
            }
            return this.illustratie;
        }

        /**
         * Gets the value of the geleideFormulier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeleideFormulier() {
            return geleideFormulier;
        }

        /**
         * Sets the value of the geleideFormulier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeleideFormulier(String value) {
            this.geleideFormulier = value;
        }

        /**
         * Gets the value of the basisURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBasisURL() {
            return basisURL;
        }

        /**
         * Sets the value of the basisURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBasisURL(String value) {
            this.basisURL = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StartPagina" type="{http://www.geonovum.nl/stri/2012/2.0}PlanSupplement" minOccurs="0"/>
     *         &lt;element name="CSS" type="{http://www.geonovum.nl/stri/2012/2.0}PlanSupplement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="BasisURL" type="{http://www.geonovum.nl/stri/2012/2.0}PlanBasisURL" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startPagina",
        "css"
    })
    public static class Supplementen {

        @XmlElement(name = "StartPagina", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected String startPagina;
        @XmlElement(name = "CSS", namespace = "http://www.geonovum.nl/stri/2012/2.0")
        @XmlSchemaType(name = "anyURI")
        protected List<String> css;
        @XmlAttribute(name = "BasisURL")
        protected String basisURL;

        /**
         * Gets the value of the startPagina property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartPagina() {
            return startPagina;
        }

        /**
         * Sets the value of the startPagina property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartPagina(String value) {
            this.startPagina = value;
        }

        /**
         * Gets the value of the css property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the css property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCSS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCSS() {
            if (css == null) {
                css = new ArrayList<String>();
            }
            return this.css;
        }

        /**
         * Gets the value of the basisURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBasisURL() {
            return basisURL;
        }

        /**
         * Sets the value of the basisURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBasisURL(String value) {
            this.basisURL = value;
        }

    }

}
