//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.01 at 01:44:26 PM CEST 
//


package nl.b3p.imro._2012._11;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for GebiedsaanduidingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GebiedsaanduidingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.geonovum.nl/imro/2012/1.1}AanduidingType">
 *       &lt;sequence>
 *         &lt;element name="naam" type="{http://www.geonovum.nl/imro/2012/1.1}GebiedsaanduidingenType"/>
 *         &lt;element name="gebiedsaanduidinggroep" type="{http://www.geonovum.nl/imro/2012/1.1}GebiedsaanduidinggroepType"/>
 *         &lt;element name="artikelnummer" type="{http://www.geonovum.nl/imro/2012/1.1}NotEmptyString"/>
 *         &lt;element name="verwijzingNaarTekstInfo" type="{http://www.geonovum.nl/imro/2012/1.1}TekstReferentie_BPPropertyType"/>
 *         &lt;element name="labelInfo" type="{http://www.geonovum.nl/imro/2012/1.1}LabelPropertyType" minOccurs="0"/>
 *         &lt;element name="geometrie" type="{http://www.geonovum.nl/imro/2012/1.1}VlakMultiVlakPropertyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GebiedsaanduidingType", propOrder = {
    "naam",
    "gebiedsaanduidinggroep",
    "artikelnummer",
    "verwijzingNaarTekstInfo",
    "labelInfo",
    "geometrie"
})
public class GebiedsaanduidingType
    extends AanduidingType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String naam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected GebiedsaanduidinggroepType gebiedsaanduidinggroep;
    @XmlElement(required = true)
    protected String artikelnummer;
    @XmlElement(required = true)
    protected TekstReferentieBPPropertyType verwijzingNaarTekstInfo;
    protected LabelPropertyType labelInfo;
    @XmlAnyElement
    protected Element geometrie;

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaam(String value) {
        this.naam = value;
    }

    /**
     * Gets the value of the gebiedsaanduidinggroep property.
     * 
     * @return
     *     possible object is
     *     {@link GebiedsaanduidinggroepType }
     *     
     */
    public GebiedsaanduidinggroepType getGebiedsaanduidinggroep() {
        return gebiedsaanduidinggroep;
    }

    /**
     * Sets the value of the gebiedsaanduidinggroep property.
     * 
     * @param value
     *     allowed object is
     *     {@link GebiedsaanduidinggroepType }
     *     
     */
    public void setGebiedsaanduidinggroep(GebiedsaanduidinggroepType value) {
        this.gebiedsaanduidinggroep = value;
    }

    /**
     * Gets the value of the artikelnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtikelnummer() {
        return artikelnummer;
    }

    /**
     * Sets the value of the artikelnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtikelnummer(String value) {
        this.artikelnummer = value;
    }

    /**
     * Gets the value of the verwijzingNaarTekstInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TekstReferentieBPPropertyType }
     *     
     */
    public TekstReferentieBPPropertyType getVerwijzingNaarTekstInfo() {
        return verwijzingNaarTekstInfo;
    }

    /**
     * Sets the value of the verwijzingNaarTekstInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TekstReferentieBPPropertyType }
     *     
     */
    public void setVerwijzingNaarTekstInfo(TekstReferentieBPPropertyType value) {
        this.verwijzingNaarTekstInfo = value;
    }

    /**
     * Gets the value of the labelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LabelPropertyType }
     *     
     */
    public LabelPropertyType getLabelInfo() {
        return labelInfo;
    }

    /**
     * Sets the value of the labelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelPropertyType }
     *     
     */
    public void setLabelInfo(LabelPropertyType value) {
        this.labelInfo = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

}
