//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 03:43:56 PM CEST 
//


package nl.b3p.imro._2012._10;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.b3p.imro._2012._10 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Functieaanduiding_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Functieaanduiding");
    private final static QName _FeatureCollectionIMRO_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "FeatureCollectionIMRO");
    private final static QName _BeleidInfoPSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "BeleidInfo_PSV");
    private final static QName _GeometrieStructuurvisieObjectP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometrieStructuurvisieObject_P");
    private final static QName _BesluitgebiedX_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitgebied_X");
    private final static QName _BesluitsubvlakA_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitsubvlak_A");
    private final static QName _NEN3610ID_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "NEN3610ID");
    private final static QName _StructuurvisiecomplexG_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiecomplex_G");
    private final static QName _GeometriePlangebiedP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometriePlangebied_P");
    private final static QName _Enkelbestemming_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Enkelbestemming");
    private final static QName _TekstReferentieBGXGB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentieBG_XGB");
    private final static QName _GeometrieBesluitobjectP3_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometrieBesluitobject_P3");
    private final static QName _GeometrieBesluitobjectP1_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometrieBesluitobject_P1");
    private final static QName _Bouwaanduiding_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Bouwaanduiding");
    private final static QName _Aanduiding_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Aanduiding");
    private final static QName _ExternPlanReferentieXGB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentie_XGB");
    private final static QName _PlanologischGebied_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "PlanologischGebied");
    private final static QName _Figuur_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Figuur");
    private final static QName _TekstReferentiePV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_PV");
    private final static QName _TekstReferentiePGSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentiePG_SV");
    private final static QName _BesluitvlakP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitvlak_P");
    private final static QName _BesluitvlakX_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitvlak_X");
    private final static QName _IllustratieReferentieBP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "IllustratieReferentie_BP");
    private final static QName _StructuurvisiegebiedR_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiegebied_R");
    private final static QName _StructuurvisiegebiedP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiegebied_P");
    private final static QName _StructuurvisiegebiedG_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiegebied_G");
    private final static QName _GeometrieBesluitobjectA_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometrieBesluitobject_A");
    private final static QName _BesluitvlakA_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitvlak_A");
    private final static QName _TekstReferentieVPSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentieV_PSV");
    private final static QName _CartografieInfo_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "CartografieInfo");
    private final static QName _TekstReferentieAMB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_AMB");
    private final static QName _ExternPlanReferentiePV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentie_PV");
    private final static QName _StructuurvisiecomplexR_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiecomplex_R");
    private final static QName _WaardeEnType_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "WaardeEnType");
    private final static QName _StructuurvisiecomplexP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisiecomplex_P");
    private final static QName _BeleidInfo_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "BeleidInfo");
    private final static QName _Gebiedsaanduiding_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Gebiedsaanduiding");
    private final static QName _TekstReferentiePGBP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentiePG_BP");
    private final static QName _Label_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Label");
    private final static QName _BesluitgebiedP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitgebied_P");
    private final static QName _TekstReferentiePSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_PSV");
    private final static QName _Bestemmingsplangebied_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Bestemmingsplangebied");
    private final static QName _IllustratieReferentie_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "IllustratieReferentie");
    private final static QName _ExternPlanReferentieAMB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentie_AMB");
    private final static QName _BesluitgebiedA_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitgebied_A");
    private final static QName _StructuurvisieverklaringP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisieverklaring_P");
    private final static QName _IllustratieReferentiePG_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "IllustratieReferentiePG");
    private final static QName _ExternPlanReferentieBP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentie_BP");
    private final static QName _PlanstatusEnDatum_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "PlanstatusEnDatum");
    private final static QName _Planobject_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Planobject");
    private final static QName _TekstReferentieSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_SV");
    private final static QName _BeleidInfoGSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "BeleidInfo_GSV");
    private final static QName _Labelpositie_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Labelpositie");
    private final static QName _SymboolEnPositie_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "SymboolEnPositie");
    private final static QName _IllustratieReferentiePSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "IllustratieReferentie_PSV");
    private final static QName _IllustratieReferentieXGB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "IllustratieReferentie_XGB");
    private final static QName _Plangebied_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Plangebied");
    private final static QName _Bouwvlak_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Bouwvlak");
    private final static QName _Dubbelbestemming_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Dubbelbestemming");
    private final static QName _TekstReferentieBGAMB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentieBG_AMB");
    private final static QName _Bestemmingsvlak_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Bestemmingsvlak");
    private final static QName _TekstReferentieXGB_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_XGB");
    private final static QName _ExternPlanReferentieSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentie_SV");
    private final static QName _Maatvoering_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Maatvoering");
    private final static QName _GeometrieStructuurvisieObject_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometrieStructuurvisieObject");
    private final static QName _StructuurvisieplangebiedR_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisieplangebied_R");
    private final static QName _StructuurvisieplangebiedP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisieplangebied_P");
    private final static QName _GeoObject_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeoObject");
    private final static QName _ExternPlanReferentiePGSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "ExternPlanReferentiePG_SV");
    private final static QName _MetadataIMRObestand_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "MetadataIMRObestand");
    private final static QName _TekstReferentieBP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentie_BP");
    private final static QName _GeometriePlangebied_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "GeometriePlangebied");
    private final static QName _TekstReferentieBGPV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "TekstReferentieBG_PV");
    private final static QName _StructuurvisieplangebiedG_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Structuurvisieplangebied_G");
    private final static QName _BesluitsubvlakX_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitsubvlak_X");
    private final static QName _OndergrondReferentie_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "OndergrondReferentie");
    private final static QName _BeleidInfoRSV_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "BeleidInfo_RSV");
    private final static QName _BesluitsubvlakP_QNAME = new QName("http://www.geonovum.nl/imro/2012/1.0", "Besluitsubvlak_P");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.b3p.imro._2012._10
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FeatureCollectionIMROType }
     * 
     */
    public FeatureCollectionIMROType createFeatureCollectionIMROType() {
        return new FeatureCollectionIMROType();
    }

    /**
     * Create an instance of {@link NEN3610IDType }
     * 
     */
    public NEN3610IDType createNEN3610IDType() {
        return new NEN3610IDType();
    }

    /**
     * Create an instance of {@link BesluitgebiedXType }
     * 
     */
    public BesluitgebiedXType createBesluitgebiedXType() {
        return new BesluitgebiedXType();
    }

    /**
     * Create an instance of {@link GeometrieStructuurvisieObjectPType }
     * 
     */
    public GeometrieStructuurvisieObjectPType createGeometrieStructuurvisieObjectPType() {
        return new GeometrieStructuurvisieObjectPType();
    }

    /**
     * Create an instance of {@link TekstReferentieSVType }
     * 
     */
    public TekstReferentieSVType createTekstReferentieSVType() {
        return new TekstReferentieSVType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakAType }
     * 
     */
    public BesluitsubvlakAType createBesluitsubvlakAType() {
        return new BesluitsubvlakAType();
    }

    /**
     * Create an instance of {@link LabelpositieType }
     * 
     */
    public LabelpositieType createLabelpositieType() {
        return new LabelpositieType();
    }

    /**
     * Create an instance of {@link GeometriePlangebiedPType }
     * 
     */
    public GeometriePlangebiedPType createGeometriePlangebiedPType() {
        return new GeometriePlangebiedPType();
    }

    /**
     * Create an instance of {@link StructuurvisiecomplexGType }
     * 
     */
    public StructuurvisiecomplexGType createStructuurvisiecomplexGType() {
        return new StructuurvisiecomplexGType();
    }

    /**
     * Create an instance of {@link BeleidInfoGSVType }
     * 
     */
    public BeleidInfoGSVType createBeleidInfoGSVType() {
        return new BeleidInfoGSVType();
    }

    /**
     * Create an instance of {@link IllustratieReferentiePGType }
     * 
     */
    public IllustratieReferentiePGType createIllustratieReferentiePGType() {
        return new IllustratieReferentiePGType();
    }

    /**
     * Create an instance of {@link BeleidInfoPSVType }
     * 
     */
    public BeleidInfoPSVType createBeleidInfoPSVType() {
        return new BeleidInfoPSVType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieBPType }
     * 
     */
    public ExternPlanReferentieBPType createExternPlanReferentieBPType() {
        return new ExternPlanReferentieBPType();
    }

    /**
     * Create an instance of {@link FunctieaanduidingType }
     * 
     */
    public FunctieaanduidingType createFunctieaanduidingType() {
        return new FunctieaanduidingType();
    }

    /**
     * Create an instance of {@link PlanstatusEnDatumType }
     * 
     */
    public PlanstatusEnDatumType createPlanstatusEnDatumType() {
        return new PlanstatusEnDatumType();
    }

    /**
     * Create an instance of {@link FiguurType }
     * 
     */
    public FiguurType createFiguurType() {
        return new FiguurType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGAMBType }
     * 
     */
    public TekstReferentieBGAMBType createTekstReferentieBGAMBType() {
        return new TekstReferentieBGAMBType();
    }

    /**
     * Create an instance of {@link DubbelbestemmingType }
     * 
     */
    public DubbelbestemmingType createDubbelbestemmingType() {
        return new DubbelbestemmingType();
    }

    /**
     * Create an instance of {@link TekstReferentiePGSVType }
     * 
     */
    public TekstReferentiePGSVType createTekstReferentiePGSVType() {
        return new TekstReferentiePGSVType();
    }

    /**
     * Create an instance of {@link BouwvlakType }
     * 
     */
    public BouwvlakType createBouwvlakType() {
        return new BouwvlakType();
    }

    /**
     * Create an instance of {@link TekstReferentiePVType }
     * 
     */
    public TekstReferentiePVType createTekstReferentiePVType() {
        return new TekstReferentiePVType();
    }

    /**
     * Create an instance of {@link IllustratieReferentieXGBType }
     * 
     */
    public IllustratieReferentieXGBType createIllustratieReferentieXGBType() {
        return new IllustratieReferentieXGBType();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectP3Type }
     * 
     */
    public GeometrieBesluitobjectP3Type createGeometrieBesluitobjectP3Type() {
        return new GeometrieBesluitobjectP3Type();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectP1Type }
     * 
     */
    public GeometrieBesluitobjectP1Type createGeometrieBesluitobjectP1Type() {
        return new GeometrieBesluitobjectP1Type();
    }

    /**
     * Create an instance of {@link EnkelbestemmingType }
     * 
     */
    public EnkelbestemmingType createEnkelbestemmingType() {
        return new EnkelbestemmingType();
    }

    /**
     * Create an instance of {@link SymboolEnPositieType }
     * 
     */
    public SymboolEnPositieType createSymboolEnPositieType() {
        return new SymboolEnPositieType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGXGBType }
     * 
     */
    public TekstReferentieBGXGBType createTekstReferentieBGXGBType() {
        return new TekstReferentieBGXGBType();
    }

    /**
     * Create an instance of {@link IllustratieReferentiePSVType }
     * 
     */
    public IllustratieReferentiePSVType createIllustratieReferentiePSVType() {
        return new IllustratieReferentiePSVType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieXGBType }
     * 
     */
    public ExternPlanReferentieXGBType createExternPlanReferentieXGBType() {
        return new ExternPlanReferentieXGBType();
    }

    /**
     * Create an instance of {@link BouwaanduidingType }
     * 
     */
    public BouwaanduidingType createBouwaanduidingType() {
        return new BouwaanduidingType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedRType }
     * 
     */
    public StructuurvisieplangebiedRType createStructuurvisieplangebiedRType() {
        return new StructuurvisieplangebiedRType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedPType }
     * 
     */
    public StructuurvisieplangebiedPType createStructuurvisieplangebiedPType() {
        return new StructuurvisieplangebiedPType();
    }

    /**
     * Create an instance of {@link BesluitvlakAType }
     * 
     */
    public BesluitvlakAType createBesluitvlakAType() {
        return new BesluitvlakAType();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectAType }
     * 
     */
    public GeometrieBesluitobjectAType createGeometrieBesluitobjectAType() {
        return new GeometrieBesluitobjectAType();
    }

    /**
     * Create an instance of {@link MaatvoeringType }
     * 
     */
    public MaatvoeringType createMaatvoeringType() {
        return new MaatvoeringType();
    }

    /**
     * Create an instance of {@link StructuurvisiegebiedGType }
     * 
     */
    public StructuurvisiegebiedGType createStructuurvisiegebiedGType() {
        return new StructuurvisiegebiedGType();
    }

    /**
     * Create an instance of {@link GeometrieStructuurvisieObjectType }
     * 
     */
    public GeometrieStructuurvisieObjectType createGeometrieStructuurvisieObjectType() {
        return new GeometrieStructuurvisieObjectType();
    }

    /**
     * Create an instance of {@link TekstReferentieVPSVType }
     * 
     */
    public TekstReferentieVPSVType createTekstReferentieVPSVType() {
        return new TekstReferentieVPSVType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentiePVType }
     * 
     */
    public ExternPlanReferentiePVType createExternPlanReferentiePVType() {
        return new ExternPlanReferentiePVType();
    }

    /**
     * Create an instance of {@link GeometriePlangebiedType }
     * 
     */
    public GeometriePlangebiedType createGeometriePlangebiedType() {
        return new GeometriePlangebiedType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGPVType }
     * 
     */
    public TekstReferentieBGPVType createTekstReferentieBGPVType() {
        return new TekstReferentieBGPVType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedGType }
     * 
     */
    public StructuurvisieplangebiedGType createStructuurvisieplangebiedGType() {
        return new StructuurvisieplangebiedGType();
    }

    /**
     * Create an instance of {@link CartografieInfoType }
     * 
     */
    public CartografieInfoType createCartografieInfoType() {
        return new CartografieInfoType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentiePGSVType }
     * 
     */
    public ExternPlanReferentiePGSVType createExternPlanReferentiePGSVType() {
        return new ExternPlanReferentiePGSVType();
    }

    /**
     * Create an instance of {@link MetadataIMRObestandType }
     * 
     */
    public MetadataIMRObestandType createMetadataIMRObestandType() {
        return new MetadataIMRObestandType();
    }

    /**
     * Create an instance of {@link TekstReferentieBPType }
     * 
     */
    public TekstReferentieBPType createTekstReferentieBPType() {
        return new TekstReferentieBPType();
    }

    /**
     * Create an instance of {@link TekstReferentieAMBType }
     * 
     */
    public TekstReferentieAMBType createTekstReferentieAMBType() {
        return new TekstReferentieAMBType();
    }

    /**
     * Create an instance of {@link TekstReferentieXGBType }
     * 
     */
    public TekstReferentieXGBType createTekstReferentieXGBType() {
        return new TekstReferentieXGBType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieSVType }
     * 
     */
    public ExternPlanReferentieSVType createExternPlanReferentieSVType() {
        return new ExternPlanReferentieSVType();
    }

    /**
     * Create an instance of {@link BesluitvlakPType }
     * 
     */
    public BesluitvlakPType createBesluitvlakPType() {
        return new BesluitvlakPType();
    }

    /**
     * Create an instance of {@link StructuurvisiegebiedRType }
     * 
     */
    public StructuurvisiegebiedRType createStructuurvisiegebiedRType() {
        return new StructuurvisiegebiedRType();
    }

    /**
     * Create an instance of {@link StructuurvisiegebiedPType }
     * 
     */
    public StructuurvisiegebiedPType createStructuurvisiegebiedPType() {
        return new StructuurvisiegebiedPType();
    }

    /**
     * Create an instance of {@link BesluitvlakXType }
     * 
     */
    public BesluitvlakXType createBesluitvlakXType() {
        return new BesluitvlakXType();
    }

    /**
     * Create an instance of {@link IllustratieReferentieBPType }
     * 
     */
    public IllustratieReferentieBPType createIllustratieReferentieBPType() {
        return new IllustratieReferentieBPType();
    }

    /**
     * Create an instance of {@link BestemmingsplangebiedType }
     * 
     */
    public BestemmingsplangebiedType createBestemmingsplangebiedType() {
        return new BestemmingsplangebiedType();
    }

    /**
     * Create an instance of {@link IllustratieReferentieType }
     * 
     */
    public IllustratieReferentieType createIllustratieReferentieType() {
        return new IllustratieReferentieType();
    }

    /**
     * Create an instance of {@link TekstReferentiePSVType }
     * 
     */
    public TekstReferentiePSVType createTekstReferentiePSVType() {
        return new TekstReferentiePSVType();
    }

    /**
     * Create an instance of {@link BeleidInfoRSVType }
     * 
     */
    public BeleidInfoRSVType createBeleidInfoRSVType() {
        return new BeleidInfoRSVType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakPType }
     * 
     */
    public BesluitsubvlakPType createBesluitsubvlakPType() {
        return new BesluitsubvlakPType();
    }

    /**
     * Create an instance of {@link BesluitgebiedAType }
     * 
     */
    public BesluitgebiedAType createBesluitgebiedAType() {
        return new BesluitgebiedAType();
    }

    /**
     * Create an instance of {@link StructuurvisieverklaringPType }
     * 
     */
    public StructuurvisieverklaringPType createStructuurvisieverklaringPType() {
        return new StructuurvisieverklaringPType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieAMBType }
     * 
     */
    public ExternPlanReferentieAMBType createExternPlanReferentieAMBType() {
        return new ExternPlanReferentieAMBType();
    }

    /**
     * Create an instance of {@link StructuurvisiecomplexPType }
     * 
     */
    public StructuurvisiecomplexPType createStructuurvisiecomplexPType() {
        return new StructuurvisiecomplexPType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakXType }
     * 
     */
    public BesluitsubvlakXType createBesluitsubvlakXType() {
        return new BesluitsubvlakXType();
    }

    /**
     * Create an instance of {@link BeleidInfoType }
     * 
     */
    public BeleidInfoType createBeleidInfoType() {
        return new BeleidInfoType();
    }

    /**
     * Create an instance of {@link OndergrondReferentieType }
     * 
     */
    public OndergrondReferentieType createOndergrondReferentieType() {
        return new OndergrondReferentieType();
    }

    /**
     * Create an instance of {@link GebiedsaanduidingType }
     * 
     */
    public GebiedsaanduidingType createGebiedsaanduidingType() {
        return new GebiedsaanduidingType();
    }

    /**
     * Create an instance of {@link StructuurvisiecomplexRType }
     * 
     */
    public StructuurvisiecomplexRType createStructuurvisiecomplexRType() {
        return new StructuurvisiecomplexRType();
    }

    /**
     * Create an instance of {@link WaardeEnTypeType }
     * 
     */
    public WaardeEnTypeType createWaardeEnTypeType() {
        return new WaardeEnTypeType();
    }

    /**
     * Create an instance of {@link TekstReferentiePGBPType }
     * 
     */
    public TekstReferentiePGBPType createTekstReferentiePGBPType() {
        return new TekstReferentiePGBPType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link BesluitgebiedPType }
     * 
     */
    public BesluitgebiedPType createBesluitgebiedPType() {
        return new BesluitgebiedPType();
    }

    /**
     * Create an instance of {@link LijnMultiLijnPropertyType }
     * 
     */
    public LijnMultiLijnPropertyType createLijnMultiLijnPropertyType() {
        return new LijnMultiLijnPropertyType();
    }

    /**
     * Create an instance of {@link BestemmingsvlakPropertyType }
     * 
     */
    public BestemmingsvlakPropertyType createBestemmingsvlakPropertyType() {
        return new BestemmingsvlakPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGAMBPropertyType }
     * 
     */
    public TekstReferentieBGAMBPropertyType createTekstReferentieBGAMBPropertyType() {
        return new TekstReferentieBGAMBPropertyType();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectP3PropertyType }
     * 
     */
    public GeometrieBesluitobjectP3PropertyType createGeometrieBesluitobjectP3PropertyType() {
        return new GeometrieBesluitobjectP3PropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieBPPropertyType }
     * 
     */
    public TekstReferentieBPPropertyType createTekstReferentieBPPropertyType() {
        return new TekstReferentieBPPropertyType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedGPropertyType }
     * 
     */
    public StructuurvisieplangebiedGPropertyType createStructuurvisieplangebiedGPropertyType() {
        return new StructuurvisieplangebiedGPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGPVPropertyType }
     * 
     */
    public TekstReferentieBGPVPropertyType createTekstReferentieBGPVPropertyType() {
        return new TekstReferentieBGPVPropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieAMBPropertyType }
     * 
     */
    public ExternPlanReferentieAMBPropertyType createExternPlanReferentieAMBPropertyType() {
        return new ExternPlanReferentieAMBPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentiePVPropertyType }
     * 
     */
    public TekstReferentiePVPropertyType createTekstReferentiePVPropertyType() {
        return new TekstReferentiePVPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieSVPropertyType }
     * 
     */
    public TekstReferentieSVPropertyType createTekstReferentieSVPropertyType() {
        return new TekstReferentieSVPropertyType();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectAPropertyType }
     * 
     */
    public GeometrieBesluitobjectAPropertyType createGeometrieBesluitobjectAPropertyType() {
        return new GeometrieBesluitobjectAPropertyType();
    }

    /**
     * Create an instance of {@link BesluitvlakPPropertyType }
     * 
     */
    public BesluitvlakPPropertyType createBesluitvlakPPropertyType() {
        return new BesluitvlakPPropertyType();
    }

    /**
     * Create an instance of {@link LabelpositiePropertyType }
     * 
     */
    public LabelpositiePropertyType createLabelpositiePropertyType() {
        return new LabelpositiePropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieVPSVPropertyType }
     * 
     */
    public TekstReferentieVPSVPropertyType createTekstReferentieVPSVPropertyType() {
        return new TekstReferentieVPSVPropertyType();
    }

    /**
     * Create an instance of {@link PlanstatusEnDatumPropertyType }
     * 
     */
    public PlanstatusEnDatumPropertyType createPlanstatusEnDatumPropertyType() {
        return new PlanstatusEnDatumPropertyType();
    }

    /**
     * Create an instance of {@link PuntLijnVlakMultiPropertyType }
     * 
     */
    public PuntLijnVlakMultiPropertyType createPuntLijnVlakMultiPropertyType() {
        return new PuntLijnVlakMultiPropertyType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedPPropertyType }
     * 
     */
    public StructuurvisieplangebiedPPropertyType createStructuurvisieplangebiedPPropertyType() {
        return new StructuurvisieplangebiedPPropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentiePGSVPropertyType }
     * 
     */
    public ExternPlanReferentiePGSVPropertyType createExternPlanReferentiePGSVPropertyType() {
        return new ExternPlanReferentiePGSVPropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieBPPropertyType }
     * 
     */
    public ExternPlanReferentieBPPropertyType createExternPlanReferentieBPPropertyType() {
        return new ExternPlanReferentieBPPropertyType();
    }

    /**
     * Create an instance of {@link WaardeEnTypePropertyType }
     * 
     */
    public WaardeEnTypePropertyType createWaardeEnTypePropertyType() {
        return new WaardeEnTypePropertyType();
    }

    /**
     * Create an instance of {@link GeometrieStructuurvisieObjectPropertyType }
     * 
     */
    public GeometrieStructuurvisieObjectPropertyType createGeometrieStructuurvisieObjectPropertyType() {
        return new GeometrieStructuurvisieObjectPropertyType();
    }

    /**
     * Create an instance of {@link PlanobjectPropertyType }
     * 
     */
    public PlanobjectPropertyType createPlanobjectPropertyType() {
        return new PlanobjectPropertyType();
    }

    /**
     * Create an instance of {@link CartografieInfoPropertyType }
     * 
     */
    public CartografieInfoPropertyType createCartografieInfoPropertyType() {
        return new CartografieInfoPropertyType();
    }

    /**
     * Create an instance of {@link BeleidInfoGSVPropertyType }
     * 
     */
    public BeleidInfoGSVPropertyType createBeleidInfoGSVPropertyType() {
        return new BeleidInfoGSVPropertyType();
    }

    /**
     * Create an instance of {@link BesluitvlakXPropertyType }
     * 
     */
    public BesluitvlakXPropertyType createBesluitvlakXPropertyType() {
        return new BesluitvlakXPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieBGXGBPropertyType }
     * 
     */
    public TekstReferentieBGXGBPropertyType createTekstReferentieBGXGBPropertyType() {
        return new TekstReferentieBGXGBPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentiePGBPPropertyType }
     * 
     */
    public TekstReferentiePGBPPropertyType createTekstReferentiePGBPPropertyType() {
        return new TekstReferentiePGBPPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieXGBPropertyType }
     * 
     */
    public TekstReferentieXGBPropertyType createTekstReferentieXGBPropertyType() {
        return new TekstReferentieXGBPropertyType();
    }

    /**
     * Create an instance of {@link NEN3610IDPropertyType }
     * 
     */
    public NEN3610IDPropertyType createNEN3610IDPropertyType() {
        return new NEN3610IDPropertyType();
    }

    /**
     * Create an instance of {@link VlakMultiVlakPropertyType }
     * 
     */
    public VlakMultiVlakPropertyType createVlakMultiVlakPropertyType() {
        return new VlakMultiVlakPropertyType();
    }

    /**
     * Create an instance of {@link IllustratieReferentiePSVPropertyType }
     * 
     */
    public IllustratieReferentiePSVPropertyType createIllustratieReferentiePSVPropertyType() {
        return new IllustratieReferentiePSVPropertyType();
    }

    /**
     * Create an instance of {@link BesluitgebiedXPropertyType }
     * 
     */
    public BesluitgebiedXPropertyType createBesluitgebiedXPropertyType() {
        return new BesluitgebiedXPropertyType();
    }

    /**
     * Create an instance of {@link BesluitgebiedPPropertyType }
     * 
     */
    public BesluitgebiedPPropertyType createBesluitgebiedPPropertyType() {
        return new BesluitgebiedPPropertyType();
    }

    /**
     * Create an instance of {@link IllustratieReferentieBPPropertyType }
     * 
     */
    public IllustratieReferentieBPPropertyType createIllustratieReferentieBPPropertyType() {
        return new IllustratieReferentieBPPropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieSVPropertyType }
     * 
     */
    public ExternPlanReferentieSVPropertyType createExternPlanReferentieSVPropertyType() {
        return new ExternPlanReferentieSVPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentiePSVPropertyType }
     * 
     */
    public TekstReferentiePSVPropertyType createTekstReferentiePSVPropertyType() {
        return new TekstReferentiePSVPropertyType();
    }

    /**
     * Create an instance of {@link GeometriePlangebiedPPropertyType }
     * 
     */
    public GeometriePlangebiedPPropertyType createGeometriePlangebiedPPropertyType() {
        return new GeometriePlangebiedPPropertyType();
    }

    /**
     * Create an instance of {@link LabelPropertyType }
     * 
     */
    public LabelPropertyType createLabelPropertyType() {
        return new LabelPropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentiePVPropertyType }
     * 
     */
    public ExternPlanReferentiePVPropertyType createExternPlanReferentiePVPropertyType() {
        return new ExternPlanReferentiePVPropertyType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakPPropertyType }
     * 
     */
    public BesluitsubvlakPPropertyType createBesluitsubvlakPPropertyType() {
        return new BesluitsubvlakPPropertyType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakXPropertyType }
     * 
     */
    public BesluitsubvlakXPropertyType createBesluitsubvlakXPropertyType() {
        return new BesluitsubvlakXPropertyType();
    }

    /**
     * Create an instance of {@link BesluitvlakAPropertyType }
     * 
     */
    public BesluitvlakAPropertyType createBesluitvlakAPropertyType() {
        return new BesluitvlakAPropertyType();
    }

    /**
     * Create an instance of {@link BestemmingsplangebiedPropertyType }
     * 
     */
    public BestemmingsplangebiedPropertyType createBestemmingsplangebiedPropertyType() {
        return new BestemmingsplangebiedPropertyType();
    }

    /**
     * Create an instance of {@link OndergrondReferentiePropertyType }
     * 
     */
    public OndergrondReferentiePropertyType createOndergrondReferentiePropertyType() {
        return new OndergrondReferentiePropertyType();
    }

    /**
     * Create an instance of {@link ExternPlanReferentieXGBPropertyType }
     * 
     */
    public ExternPlanReferentieXGBPropertyType createExternPlanReferentieXGBPropertyType() {
        return new ExternPlanReferentieXGBPropertyType();
    }

    /**
     * Create an instance of {@link BesluitgebiedAPropertyType }
     * 
     */
    public BesluitgebiedAPropertyType createBesluitgebiedAPropertyType() {
        return new BesluitgebiedAPropertyType();
    }

    /**
     * Create an instance of {@link IllustratieReferentiePropertyType }
     * 
     */
    public IllustratieReferentiePropertyType createIllustratieReferentiePropertyType() {
        return new IllustratieReferentiePropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentieAMBPropertyType }
     * 
     */
    public TekstReferentieAMBPropertyType createTekstReferentieAMBPropertyType() {
        return new TekstReferentieAMBPropertyType();
    }

    /**
     * Create an instance of {@link BeleidInfoPSVPropertyType }
     * 
     */
    public BeleidInfoPSVPropertyType createBeleidInfoPSVPropertyType() {
        return new BeleidInfoPSVPropertyType();
    }

    /**
     * Create an instance of {@link BeleidInfoRSVPropertyType }
     * 
     */
    public BeleidInfoRSVPropertyType createBeleidInfoRSVPropertyType() {
        return new BeleidInfoRSVPropertyType();
    }

    /**
     * Create an instance of {@link GeometrieBesluitobjectP1PropertyType }
     * 
     */
    public GeometrieBesluitobjectP1PropertyType createGeometrieBesluitobjectP1PropertyType() {
        return new GeometrieBesluitobjectP1PropertyType();
    }

    /**
     * Create an instance of {@link IllustratieReferentieXGBPropertyType }
     * 
     */
    public IllustratieReferentieXGBPropertyType createIllustratieReferentieXGBPropertyType() {
        return new IllustratieReferentieXGBPropertyType();
    }

    /**
     * Create an instance of {@link IllustratieReferentiePGPropertyType }
     * 
     */
    public IllustratieReferentiePGPropertyType createIllustratieReferentiePGPropertyType() {
        return new IllustratieReferentiePGPropertyType();
    }

    /**
     * Create an instance of {@link GeometriePlangebiedPropertyType }
     * 
     */
    public GeometriePlangebiedPropertyType createGeometriePlangebiedPropertyType() {
        return new GeometriePlangebiedPropertyType();
    }

    /**
     * Create an instance of {@link SymboolEnPositiePropertyType }
     * 
     */
    public SymboolEnPositiePropertyType createSymboolEnPositiePropertyType() {
        return new SymboolEnPositiePropertyType();
    }

    /**
     * Create an instance of {@link GeometrieStructuurvisieObjectPPropertyType }
     * 
     */
    public GeometrieStructuurvisieObjectPPropertyType createGeometrieStructuurvisieObjectPPropertyType() {
        return new GeometrieStructuurvisieObjectPPropertyType();
    }

    /**
     * Create an instance of {@link StructuurvisieplangebiedRPropertyType }
     * 
     */
    public StructuurvisieplangebiedRPropertyType createStructuurvisieplangebiedRPropertyType() {
        return new StructuurvisieplangebiedRPropertyType();
    }

    /**
     * Create an instance of {@link TekstReferentiePGSVPropertyType }
     * 
     */
    public TekstReferentiePGSVPropertyType createTekstReferentiePGSVPropertyType() {
        return new TekstReferentiePGSVPropertyType();
    }

    /**
     * Create an instance of {@link AanduidingPropertyType }
     * 
     */
    public AanduidingPropertyType createAanduidingPropertyType() {
        return new AanduidingPropertyType();
    }

    /**
     * Create an instance of {@link BesluitsubvlakAPropertyType }
     * 
     */
    public BesluitsubvlakAPropertyType createBesluitsubvlakAPropertyType() {
        return new BesluitsubvlakAPropertyType();
    }

    /**
     * Create an instance of {@link FeatureCollectionIMROType.FeatureMember }
     * 
     */
    public FeatureCollectionIMROType.FeatureMember createFeatureCollectionIMROTypeFeatureMember() {
        return new FeatureCollectionIMROType.FeatureMember();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FunctieaanduidingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Functieaanduiding", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<FunctieaanduidingType> createFunctieaanduiding(FunctieaanduidingType value) {
        return new JAXBElement<FunctieaanduidingType>(_Functieaanduiding_QNAME, FunctieaanduidingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeatureCollectionIMROType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "FeatureCollectionIMRO", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<FeatureCollectionIMROType> createFeatureCollectionIMRO(FeatureCollectionIMROType value) {
        return new JAXBElement<FeatureCollectionIMROType>(_FeatureCollectionIMRO_QNAME, FeatureCollectionIMROType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeleidInfoPSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "BeleidInfo_PSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<BeleidInfoPSVType> createBeleidInfoPSV(BeleidInfoPSVType value) {
        return new JAXBElement<BeleidInfoPSVType>(_BeleidInfoPSV_QNAME, BeleidInfoPSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometrieStructuurvisieObjectPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometrieStructuurvisieObject_P", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometrieStructuurvisieObjectPType> createGeometrieStructuurvisieObjectP(GeometrieStructuurvisieObjectPType value) {
        return new JAXBElement<GeometrieStructuurvisieObjectPType>(_GeometrieStructuurvisieObjectP_QNAME, GeometrieStructuurvisieObjectPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitgebiedXType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitgebied_X", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<BesluitgebiedXType> createBesluitgebiedX(BesluitgebiedXType value) {
        return new JAXBElement<BesluitgebiedXType>(_BesluitgebiedX_QNAME, BesluitgebiedXType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitsubvlakAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitsubvlak_A", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitsubvlakAType> createBesluitsubvlakA(BesluitsubvlakAType value) {
        return new JAXBElement<BesluitsubvlakAType>(_BesluitsubvlakA_QNAME, BesluitsubvlakAType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NEN3610IDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "NEN3610ID", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<NEN3610IDType> createNEN3610ID(NEN3610IDType value) {
        return new JAXBElement<NEN3610IDType>(_NEN3610ID_QNAME, NEN3610IDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiecomplexGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiecomplex_G", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiecomplexGType> createStructuurvisiecomplexG(StructuurvisiecomplexGType value) {
        return new JAXBElement<StructuurvisiecomplexGType>(_StructuurvisiecomplexG_QNAME, StructuurvisiecomplexGType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometriePlangebiedPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometriePlangebied_P", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometriePlangebiedPType> createGeometriePlangebiedP(GeometriePlangebiedPType value) {
        return new JAXBElement<GeometriePlangebiedPType>(_GeometriePlangebiedP_QNAME, GeometriePlangebiedPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnkelbestemmingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Enkelbestemming", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Bestemmingsvlak")
    public JAXBElement<EnkelbestemmingType> createEnkelbestemming(EnkelbestemmingType value) {
        return new JAXBElement<EnkelbestemmingType>(_Enkelbestemming_QNAME, EnkelbestemmingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieBGXGBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentieBG_XGB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieBGXGBType> createTekstReferentieBGXGB(TekstReferentieBGXGBType value) {
        return new JAXBElement<TekstReferentieBGXGBType>(_TekstReferentieBGXGB_QNAME, TekstReferentieBGXGBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometrieBesluitobjectP3Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometrieBesluitobject_P3", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometrieBesluitobjectP3Type> createGeometrieBesluitobjectP3(GeometrieBesluitobjectP3Type value) {
        return new JAXBElement<GeometrieBesluitobjectP3Type>(_GeometrieBesluitobjectP3_QNAME, GeometrieBesluitobjectP3Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometrieBesluitobjectP1Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometrieBesluitobject_P1", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometrieBesluitobjectP1Type> createGeometrieBesluitobjectP1(GeometrieBesluitobjectP1Type value) {
        return new JAXBElement<GeometrieBesluitobjectP1Type>(_GeometrieBesluitobjectP1_QNAME, GeometrieBesluitobjectP1Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BouwaanduidingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Bouwaanduiding", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<BouwaanduidingType> createBouwaanduiding(BouwaanduidingType value) {
        return new JAXBElement<BouwaanduidingType>(_Bouwaanduiding_QNAME, BouwaanduidingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AanduidingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Aanduiding", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<AanduidingType> createAanduiding(AanduidingType value) {
        return new JAXBElement<AanduidingType>(_Aanduiding_QNAME, AanduidingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentieXGBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentie_XGB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentieXGBType> createExternPlanReferentieXGB(ExternPlanReferentieXGBType value) {
        return new JAXBElement<ExternPlanReferentieXGBType>(_ExternPlanReferentieXGB_QNAME, ExternPlanReferentieXGBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlanologischGebiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "PlanologischGebied", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "GeoObject")
    public JAXBElement<PlanologischGebiedType> createPlanologischGebied(PlanologischGebiedType value) {
        return new JAXBElement<PlanologischGebiedType>(_PlanologischGebied_QNAME, PlanologischGebiedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FiguurType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Figuur", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<FiguurType> createFiguur(FiguurType value) {
        return new JAXBElement<FiguurType>(_Figuur_QNAME, FiguurType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentiePVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_PV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentiePVType> createTekstReferentiePV(TekstReferentiePVType value) {
        return new JAXBElement<TekstReferentiePVType>(_TekstReferentiePV_QNAME, TekstReferentiePVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentiePGSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentiePG_SV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentiePGSVType> createTekstReferentiePGSV(TekstReferentiePGSVType value) {
        return new JAXBElement<TekstReferentiePGSVType>(_TekstReferentiePGSV_QNAME, TekstReferentiePGSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitvlakPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitvlak_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitvlakPType> createBesluitvlakP(BesluitvlakPType value) {
        return new JAXBElement<BesluitvlakPType>(_BesluitvlakP_QNAME, BesluitvlakPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitvlakXType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitvlak_X", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitvlakXType> createBesluitvlakX(BesluitvlakXType value) {
        return new JAXBElement<BesluitvlakXType>(_BesluitvlakX_QNAME, BesluitvlakXType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IllustratieReferentieBPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "IllustratieReferentie_BP", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<IllustratieReferentieBPType> createIllustratieReferentieBP(IllustratieReferentieBPType value) {
        return new JAXBElement<IllustratieReferentieBPType>(_IllustratieReferentieBP_QNAME, IllustratieReferentieBPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiegebiedRType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiegebied_R", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiegebiedRType> createStructuurvisiegebiedR(StructuurvisiegebiedRType value) {
        return new JAXBElement<StructuurvisiegebiedRType>(_StructuurvisiegebiedR_QNAME, StructuurvisiegebiedRType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiegebiedPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiegebied_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiegebiedPType> createStructuurvisiegebiedP(StructuurvisiegebiedPType value) {
        return new JAXBElement<StructuurvisiegebiedPType>(_StructuurvisiegebiedP_QNAME, StructuurvisiegebiedPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiegebiedGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiegebied_G", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiegebiedGType> createStructuurvisiegebiedG(StructuurvisiegebiedGType value) {
        return new JAXBElement<StructuurvisiegebiedGType>(_StructuurvisiegebiedG_QNAME, StructuurvisiegebiedGType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometrieBesluitobjectAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometrieBesluitobject_A", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometrieBesluitobjectAType> createGeometrieBesluitobjectA(GeometrieBesluitobjectAType value) {
        return new JAXBElement<GeometrieBesluitobjectAType>(_GeometrieBesluitobjectA_QNAME, GeometrieBesluitobjectAType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitvlakAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitvlak_A", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitvlakAType> createBesluitvlakA(BesluitvlakAType value) {
        return new JAXBElement<BesluitvlakAType>(_BesluitvlakA_QNAME, BesluitvlakAType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieVPSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentieV_PSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieVPSVType> createTekstReferentieVPSV(TekstReferentieVPSVType value) {
        return new JAXBElement<TekstReferentieVPSVType>(_TekstReferentieVPSV_QNAME, TekstReferentieVPSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CartografieInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "CartografieInfo", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<CartografieInfoType> createCartografieInfo(CartografieInfoType value) {
        return new JAXBElement<CartografieInfoType>(_CartografieInfo_QNAME, CartografieInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieAMBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_AMB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieAMBType> createTekstReferentieAMB(TekstReferentieAMBType value) {
        return new JAXBElement<TekstReferentieAMBType>(_TekstReferentieAMB_QNAME, TekstReferentieAMBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentiePVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentie_PV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentiePVType> createExternPlanReferentiePV(ExternPlanReferentiePVType value) {
        return new JAXBElement<ExternPlanReferentiePVType>(_ExternPlanReferentiePV_QNAME, ExternPlanReferentiePVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiecomplexRType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiecomplex_R", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiecomplexRType> createStructuurvisiecomplexR(StructuurvisiecomplexRType value) {
        return new JAXBElement<StructuurvisiecomplexRType>(_StructuurvisiecomplexR_QNAME, StructuurvisiecomplexRType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WaardeEnTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "WaardeEnType", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<WaardeEnTypeType> createWaardeEnType(WaardeEnTypeType value) {
        return new JAXBElement<WaardeEnTypeType>(_WaardeEnType_QNAME, WaardeEnTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisiecomplexPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisiecomplex_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisiecomplexPType> createStructuurvisiecomplexP(StructuurvisiecomplexPType value) {
        return new JAXBElement<StructuurvisiecomplexPType>(_StructuurvisiecomplexP_QNAME, StructuurvisiecomplexPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeleidInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "BeleidInfo", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<BeleidInfoType> createBeleidInfo(BeleidInfoType value) {
        return new JAXBElement<BeleidInfoType>(_BeleidInfo_QNAME, BeleidInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GebiedsaanduidingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Gebiedsaanduiding", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<GebiedsaanduidingType> createGebiedsaanduiding(GebiedsaanduidingType value) {
        return new JAXBElement<GebiedsaanduidingType>(_Gebiedsaanduiding_QNAME, GebiedsaanduidingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentiePGBPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentiePG_BP", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentiePGBPType> createTekstReferentiePGBP(TekstReferentiePGBPType value) {
        return new JAXBElement<TekstReferentiePGBPType>(_TekstReferentiePGBP_QNAME, TekstReferentiePGBPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LabelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Label", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<LabelType> createLabel(LabelType value) {
        return new JAXBElement<LabelType>(_Label_QNAME, LabelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitgebiedPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitgebied_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<BesluitgebiedPType> createBesluitgebiedP(BesluitgebiedPType value) {
        return new JAXBElement<BesluitgebiedPType>(_BesluitgebiedP_QNAME, BesluitgebiedPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentiePSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_PSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentiePSVType> createTekstReferentiePSV(TekstReferentiePSVType value) {
        return new JAXBElement<TekstReferentiePSVType>(_TekstReferentiePSV_QNAME, TekstReferentiePSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BestemmingsplangebiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Bestemmingsplangebied", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<BestemmingsplangebiedType> createBestemmingsplangebied(BestemmingsplangebiedType value) {
        return new JAXBElement<BestemmingsplangebiedType>(_Bestemmingsplangebied_QNAME, BestemmingsplangebiedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IllustratieReferentieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "IllustratieReferentie", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<IllustratieReferentieType> createIllustratieReferentie(IllustratieReferentieType value) {
        return new JAXBElement<IllustratieReferentieType>(_IllustratieReferentie_QNAME, IllustratieReferentieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentieAMBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentie_AMB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentieAMBType> createExternPlanReferentieAMB(ExternPlanReferentieAMBType value) {
        return new JAXBElement<ExternPlanReferentieAMBType>(_ExternPlanReferentieAMB_QNAME, ExternPlanReferentieAMBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitgebiedAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitgebied_A", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<BesluitgebiedAType> createBesluitgebiedA(BesluitgebiedAType value) {
        return new JAXBElement<BesluitgebiedAType>(_BesluitgebiedA_QNAME, BesluitgebiedAType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisieverklaringPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisieverklaring_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<StructuurvisieverklaringPType> createStructuurvisieverklaringP(StructuurvisieverklaringPType value) {
        return new JAXBElement<StructuurvisieverklaringPType>(_StructuurvisieverklaringP_QNAME, StructuurvisieverklaringPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IllustratieReferentiePGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "IllustratieReferentiePG", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<IllustratieReferentiePGType> createIllustratieReferentiePG(IllustratieReferentiePGType value) {
        return new JAXBElement<IllustratieReferentiePGType>(_IllustratieReferentiePG_QNAME, IllustratieReferentiePGType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentieBPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentie_BP", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentieBPType> createExternPlanReferentieBP(ExternPlanReferentieBPType value) {
        return new JAXBElement<ExternPlanReferentieBPType>(_ExternPlanReferentieBP_QNAME, ExternPlanReferentieBPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlanstatusEnDatumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "PlanstatusEnDatum", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<PlanstatusEnDatumType> createPlanstatusEnDatum(PlanstatusEnDatumType value) {
        return new JAXBElement<PlanstatusEnDatumType>(_PlanstatusEnDatum_QNAME, PlanstatusEnDatumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlanobjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Planobject", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "PlanologischGebied")
    public JAXBElement<PlanobjectType> createPlanobject(PlanobjectType value) {
        return new JAXBElement<PlanobjectType>(_Planobject_QNAME, PlanobjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_SV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieSVType> createTekstReferentieSV(TekstReferentieSVType value) {
        return new JAXBElement<TekstReferentieSVType>(_TekstReferentieSV_QNAME, TekstReferentieSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeleidInfoGSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "BeleidInfo_GSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<BeleidInfoGSVType> createBeleidInfoGSV(BeleidInfoGSVType value) {
        return new JAXBElement<BeleidInfoGSVType>(_BeleidInfoGSV_QNAME, BeleidInfoGSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LabelpositieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Labelpositie", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<LabelpositieType> createLabelpositie(LabelpositieType value) {
        return new JAXBElement<LabelpositieType>(_Labelpositie_QNAME, LabelpositieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SymboolEnPositieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "SymboolEnPositie", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<SymboolEnPositieType> createSymboolEnPositie(SymboolEnPositieType value) {
        return new JAXBElement<SymboolEnPositieType>(_SymboolEnPositie_QNAME, SymboolEnPositieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IllustratieReferentiePSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "IllustratieReferentie_PSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<IllustratieReferentiePSVType> createIllustratieReferentiePSV(IllustratieReferentiePSVType value) {
        return new JAXBElement<IllustratieReferentiePSVType>(_IllustratieReferentiePSV_QNAME, IllustratieReferentiePSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IllustratieReferentieXGBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "IllustratieReferentie_XGB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<IllustratieReferentieXGBType> createIllustratieReferentieXGB(IllustratieReferentieXGBType value) {
        return new JAXBElement<IllustratieReferentieXGBType>(_IllustratieReferentieXGB_QNAME, IllustratieReferentieXGBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlangebiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Plangebied", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "PlanologischGebied")
    public JAXBElement<PlangebiedType> createPlangebied(PlangebiedType value) {
        return new JAXBElement<PlangebiedType>(_Plangebied_QNAME, PlangebiedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BouwvlakType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Bouwvlak", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<BouwvlakType> createBouwvlak(BouwvlakType value) {
        return new JAXBElement<BouwvlakType>(_Bouwvlak_QNAME, BouwvlakType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DubbelbestemmingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Dubbelbestemming", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Bestemmingsvlak")
    public JAXBElement<DubbelbestemmingType> createDubbelbestemming(DubbelbestemmingType value) {
        return new JAXBElement<DubbelbestemmingType>(_Dubbelbestemming_QNAME, DubbelbestemmingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieBGAMBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentieBG_AMB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieBGAMBType> createTekstReferentieBGAMB(TekstReferentieBGAMBType value) {
        return new JAXBElement<TekstReferentieBGAMBType>(_TekstReferentieBGAMB_QNAME, TekstReferentieBGAMBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BestemmingsvlakType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Bestemmingsvlak", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BestemmingsvlakType> createBestemmingsvlak(BestemmingsvlakType value) {
        return new JAXBElement<BestemmingsvlakType>(_Bestemmingsvlak_QNAME, BestemmingsvlakType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieXGBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_XGB", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieXGBType> createTekstReferentieXGB(TekstReferentieXGBType value) {
        return new JAXBElement<TekstReferentieXGBType>(_TekstReferentieXGB_QNAME, TekstReferentieXGBType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentieSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentie_SV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentieSVType> createExternPlanReferentieSV(ExternPlanReferentieSVType value) {
        return new JAXBElement<ExternPlanReferentieSVType>(_ExternPlanReferentieSV_QNAME, ExternPlanReferentieSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaatvoeringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Maatvoering", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Aanduiding")
    public JAXBElement<MaatvoeringType> createMaatvoering(MaatvoeringType value) {
        return new JAXBElement<MaatvoeringType>(_Maatvoering_QNAME, MaatvoeringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometrieStructuurvisieObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometrieStructuurvisieObject", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometrieStructuurvisieObjectType> createGeometrieStructuurvisieObject(GeometrieStructuurvisieObjectType value) {
        return new JAXBElement<GeometrieStructuurvisieObjectType>(_GeometrieStructuurvisieObject_QNAME, GeometrieStructuurvisieObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisieplangebiedRType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisieplangebied_R", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<StructuurvisieplangebiedRType> createStructuurvisieplangebiedR(StructuurvisieplangebiedRType value) {
        return new JAXBElement<StructuurvisieplangebiedRType>(_StructuurvisieplangebiedR_QNAME, StructuurvisieplangebiedRType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisieplangebiedPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisieplangebied_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<StructuurvisieplangebiedPType> createStructuurvisieplangebiedP(StructuurvisieplangebiedPType value) {
        return new JAXBElement<StructuurvisieplangebiedPType>(_StructuurvisieplangebiedP_QNAME, StructuurvisieplangebiedPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeoObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeoObject", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeoObjectType> createGeoObject(GeoObjectType value) {
        return new JAXBElement<GeoObjectType>(_GeoObject_QNAME, GeoObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternPlanReferentiePGSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "ExternPlanReferentiePG_SV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<ExternPlanReferentiePGSVType> createExternPlanReferentiePGSV(ExternPlanReferentiePGSVType value) {
        return new JAXBElement<ExternPlanReferentiePGSVType>(_ExternPlanReferentiePGSV_QNAME, ExternPlanReferentiePGSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataIMRObestandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "MetadataIMRObestand", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<MetadataIMRObestandType> createMetadataIMRObestand(MetadataIMRObestandType value) {
        return new JAXBElement<MetadataIMRObestandType>(_MetadataIMRObestand_QNAME, MetadataIMRObestandType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieBPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentie_BP", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieBPType> createTekstReferentieBP(TekstReferentieBPType value) {
        return new JAXBElement<TekstReferentieBPType>(_TekstReferentieBP_QNAME, TekstReferentieBPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometriePlangebiedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "GeometriePlangebied", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<GeometriePlangebiedType> createGeometriePlangebied(GeometriePlangebiedType value) {
        return new JAXBElement<GeometriePlangebiedType>(_GeometriePlangebied_QNAME, GeometriePlangebiedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TekstReferentieBGPVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "TekstReferentieBG_PV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<TekstReferentieBGPVType> createTekstReferentieBGPV(TekstReferentieBGPVType value) {
        return new JAXBElement<TekstReferentieBGPVType>(_TekstReferentieBGPV_QNAME, TekstReferentieBGPVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuurvisieplangebiedGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Structuurvisieplangebied_G", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Plangebied")
    public JAXBElement<StructuurvisieplangebiedGType> createStructuurvisieplangebiedG(StructuurvisieplangebiedGType value) {
        return new JAXBElement<StructuurvisieplangebiedGType>(_StructuurvisieplangebiedG_QNAME, StructuurvisieplangebiedGType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitsubvlakXType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitsubvlak_X", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitsubvlakXType> createBesluitsubvlakX(BesluitsubvlakXType value) {
        return new JAXBElement<BesluitsubvlakXType>(_BesluitsubvlakX_QNAME, BesluitsubvlakXType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OndergrondReferentieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "OndergrondReferentie", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<OndergrondReferentieType> createOndergrondReferentie(OndergrondReferentieType value) {
        return new JAXBElement<OndergrondReferentieType>(_OndergrondReferentie_QNAME, OndergrondReferentieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeleidInfoRSVType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "BeleidInfo_RSV", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<BeleidInfoRSVType> createBeleidInfoRSV(BeleidInfoRSVType value) {
        return new JAXBElement<BeleidInfoRSVType>(_BeleidInfoRSV_QNAME, BeleidInfoRSVType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BesluitsubvlakPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.geonovum.nl/imro/2012/1.0", name = "Besluitsubvlak_P", substitutionHeadNamespace = "http://www.geonovum.nl/imro/2012/1.0", substitutionHeadName = "Planobject")
    public JAXBElement<BesluitsubvlakPType> createBesluitsubvlakP(BesluitsubvlakPType value) {
        return new JAXBElement<BesluitsubvlakPType>(_BesluitsubvlakP_QNAME, BesluitsubvlakPType.class, null, value);
    }

}
