//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 08:41:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geonovum.nl/imro/2012/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.b3p.imro._2012._10;
