//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 04:45:53 PM CEST 
//


package nl.b3p.imro._2006._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.CodeType;


/**
 * <p>Java class for BestemmingsvlakType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BestemmingsvlakType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ravi.nl/imro2006}PlanobjectType">
 *       &lt;sequence>
 *         &lt;element name="artikelnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="begindatumDefinitief" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bestemmingsfunctieInfo" type="{http://www.ravi.nl/imro2006}BestemmingsfunctieElementPropertyType" maxOccurs="unbounded"/>
 *         &lt;element name="bestemmingshoofdgroep" type="{http://www.ravi.nl/imro2006}HoofdbestemmingType"/>
 *         &lt;element name="einddatumVoorlopig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geometrie" type="{http://www.ravi.nl/imro2006}PuntLijnVlakPropertyType"/>
 *         &lt;element name="labelInfo" type="{http://www.ravi.nl/imro2006}LabelPropertyType" minOccurs="0"/>
 *         &lt;element name="maxHoogteliggingVlak" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="minHoogteliggingVlak" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="naam" type="{http://www.opengis.net/gml}CodeType"/>
 *         &lt;element name="verwijzingNaarTekst" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="plangebied" type="{http://www.ravi.nl/imro2006}BestemmingsplangebiedPropertyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BestemmingsvlakType", propOrder = {
    "artikelnummer",
    "begindatumDefinitief",
    "bestemmingsfunctieInfo",
    "bestemmingshoofdgroep",
    "einddatumVoorlopig",
    "geometrie",
    "labelInfo",
    "maxHoogteliggingVlak",
    "minHoogteliggingVlak",
    "naam",
    "verwijzingNaarTekst",
    "plangebied"
})
@XmlSeeAlso({
    DubbelbestemmingType.class,
    EnkelbestemmingType.class
})
public abstract class BestemmingsvlakType
    extends PlanobjectType
{

    @XmlElement(required = true)
    protected String artikelnummer;
    protected String begindatumDefinitief;
    @XmlElement(required = true)
    protected List<BestemmingsfunctieElementPropertyType> bestemmingsfunctieInfo;
    @XmlElement(required = true)
    protected HoofdbestemmingType bestemmingshoofdgroep;
    protected String einddatumVoorlopig;
    @XmlElement(required = true)
    protected PuntLijnVlakPropertyType geometrie;
    protected LabelPropertyType labelInfo;
    protected Double maxHoogteliggingVlak;
    protected Double minHoogteliggingVlak;
    @XmlElement(required = true)
    protected CodeType naam;
    @XmlElement(required = true)
    protected List<String> verwijzingNaarTekst;
    @XmlElement(required = true)
    protected BestemmingsplangebiedPropertyType plangebied;

    /**
     * Gets the value of the artikelnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtikelnummer() {
        return artikelnummer;
    }

    /**
     * Sets the value of the artikelnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtikelnummer(String value) {
        this.artikelnummer = value;
    }

    /**
     * Gets the value of the begindatumDefinitief property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegindatumDefinitief() {
        return begindatumDefinitief;
    }

    /**
     * Sets the value of the begindatumDefinitief property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBegindatumDefinitief(String value) {
        this.begindatumDefinitief = value;
    }

    /**
     * Gets the value of the bestemmingsfunctieInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bestemmingsfunctieInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBestemmingsfunctieInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BestemmingsfunctieElementPropertyType }
     * 
     * 
     */
    public List<BestemmingsfunctieElementPropertyType> getBestemmingsfunctieInfo() {
        if (bestemmingsfunctieInfo == null) {
            bestemmingsfunctieInfo = new ArrayList<BestemmingsfunctieElementPropertyType>();
        }
        return this.bestemmingsfunctieInfo;
    }

    /**
     * Gets the value of the bestemmingshoofdgroep property.
     * 
     * @return
     *     possible object is
     *     {@link HoofdbestemmingType }
     *     
     */
    public HoofdbestemmingType getBestemmingshoofdgroep() {
        return bestemmingshoofdgroep;
    }

    /**
     * Sets the value of the bestemmingshoofdgroep property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoofdbestemmingType }
     *     
     */
    public void setBestemmingshoofdgroep(HoofdbestemmingType value) {
        this.bestemmingshoofdgroep = value;
    }

    /**
     * Gets the value of the einddatumVoorlopig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEinddatumVoorlopig() {
        return einddatumVoorlopig;
    }

    /**
     * Sets the value of the einddatumVoorlopig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEinddatumVoorlopig(String value) {
        this.einddatumVoorlopig = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link PuntLijnVlakPropertyType }
     *     
     */
    public PuntLijnVlakPropertyType getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link PuntLijnVlakPropertyType }
     *     
     */
    public void setGeometrie(PuntLijnVlakPropertyType value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the labelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LabelPropertyType }
     *     
     */
    public LabelPropertyType getLabelInfo() {
        return labelInfo;
    }

    /**
     * Sets the value of the labelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelPropertyType }
     *     
     */
    public void setLabelInfo(LabelPropertyType value) {
        this.labelInfo = value;
    }

    /**
     * Gets the value of the maxHoogteliggingVlak property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxHoogteliggingVlak() {
        return maxHoogteliggingVlak;
    }

    /**
     * Sets the value of the maxHoogteliggingVlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxHoogteliggingVlak(Double value) {
        this.maxHoogteliggingVlak = value;
    }

    /**
     * Gets the value of the minHoogteliggingVlak property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinHoogteliggingVlak() {
        return minHoogteliggingVlak;
    }

    /**
     * Sets the value of the minHoogteliggingVlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinHoogteliggingVlak(Double value) {
        this.minHoogteliggingVlak = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setNaam(CodeType value) {
        this.naam = value;
    }

    /**
     * Gets the value of the verwijzingNaarTekst property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verwijzingNaarTekst property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerwijzingNaarTekst().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVerwijzingNaarTekst() {
        if (verwijzingNaarTekst == null) {
            verwijzingNaarTekst = new ArrayList<String>();
        }
        return this.verwijzingNaarTekst;
    }

    /**
     * Gets the value of the plangebied property.
     * 
     * @return
     *     possible object is
     *     {@link BestemmingsplangebiedPropertyType }
     *     
     */
    public BestemmingsplangebiedPropertyType getPlangebied() {
        return plangebied;
    }

    /**
     * Sets the value of the plangebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestemmingsplangebiedPropertyType }
     *     
     */
    public void setPlangebied(BestemmingsplangebiedPropertyType value) {
        this.plangebied = value;
    }

}
