//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 04:45:53 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="chemische stoffen"/>
 *     &lt;enumeration value="elektriciteit"/>
 *     &lt;enumeration value="gas"/>
 *     &lt;enumeration value="gas; aardgas"/>
 *     &lt;enumeration value="gas; LPG"/>
 *     &lt;enumeration value="gas; propaan"/>
 *     &lt;enumeration value="kabeltelevisie"/>
 *     &lt;enumeration value="kooldioxide"/>
 *     &lt;enumeration value="olie"/>
 *     &lt;enumeration value="olie; (ruwe) olie"/>
 *     &lt;enumeration value="olie; benzine"/>
 *     &lt;enumeration value="olie; dieselolie"/>
 *     &lt;enumeration value="olie; kerosine"/>
 *     &lt;enumeration value="olie; petroleum"/>
 *     &lt;enumeration value="telecommunicatie"/>
 *     &lt;enumeration value="warmte"/>
 *     &lt;enumeration value="water"/>
 *     &lt;enumeration value="water; drinkwater"/>
 *     &lt;enumeration value="water; grondwater"/>
 *     &lt;enumeration value="water; hemelwater"/>
 *     &lt;enumeration value="water; oppervlaktewater"/>
 *     &lt;enumeration value="water; rioolwater"/>
 *     &lt;enumeration value="water; vuilwater"/>
 *     &lt;enumeration value="water; zoutwater"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductType")
@XmlEnum
public enum ProductType {

    @XmlEnumValue("chemische stoffen")
    CHEMISCHE_STOFFEN("chemische stoffen"),
    @XmlEnumValue("elektriciteit")
    ELEKTRICITEIT("elektriciteit"),
    @XmlEnumValue("gas")
    GAS("gas"),
    @XmlEnumValue("gas; aardgas")
    GAS_AARDGAS("gas; aardgas"),
    @XmlEnumValue("gas; LPG")
    GAS_LPG("gas; LPG"),
    @XmlEnumValue("gas; propaan")
    GAS_PROPAAN("gas; propaan"),
    @XmlEnumValue("kabeltelevisie")
    KABELTELEVISIE("kabeltelevisie"),
    @XmlEnumValue("kooldioxide")
    KOOLDIOXIDE("kooldioxide"),
    @XmlEnumValue("olie")
    OLIE("olie"),
    @XmlEnumValue("olie; (ruwe) olie")
    OLIE_RUWE_OLIE("olie; (ruwe) olie"),
    @XmlEnumValue("olie; benzine")
    OLIE_BENZINE("olie; benzine"),
    @XmlEnumValue("olie; dieselolie")
    OLIE_DIESELOLIE("olie; dieselolie"),
    @XmlEnumValue("olie; kerosine")
    OLIE_KEROSINE("olie; kerosine"),
    @XmlEnumValue("olie; petroleum")
    OLIE_PETROLEUM("olie; petroleum"),
    @XmlEnumValue("telecommunicatie")
    TELECOMMUNICATIE("telecommunicatie"),
    @XmlEnumValue("warmte")
    WARMTE("warmte"),
    @XmlEnumValue("water")
    WATER("water"),
    @XmlEnumValue("water; drinkwater")
    WATER_DRINKWATER("water; drinkwater"),
    @XmlEnumValue("water; grondwater")
    WATER_GRONDWATER("water; grondwater"),
    @XmlEnumValue("water; hemelwater")
    WATER_HEMELWATER("water; hemelwater"),
    @XmlEnumValue("water; oppervlaktewater")
    WATER_OPPERVLAKTEWATER("water; oppervlaktewater"),
    @XmlEnumValue("water; rioolwater")
    WATER_RIOOLWATER("water; rioolwater"),
    @XmlEnumValue("water; vuilwater")
    WATER_VUILWATER("water; vuilwater"),
    @XmlEnumValue("water; zoutwater")
    WATER_ZOUTWATER("water; zoutwater");
    private final String value;

    ProductType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductType fromValue(String v) {
        for (ProductType c: ProductType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
