//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 02:05:22 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AanduidingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AanduidingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ravi.nl/imro2006}PlanobjectType">
 *       &lt;sequence>
 *         &lt;element name="naam" type="{http://www.opengis.net/gml}CodeType"/>
 *         &lt;element name="plangebied" type="{http://www.ravi.nl/imro2006}BestemmingsplangebiedPropertyType"/>
 *         &lt;element name="bestemmingsvlak" type="{http://www.ravi.nl/imro2006}BestemmingsvlakPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AanduidingType", propOrder = {
    "naam",
    "plangebied",
    "bestemmingsvlak"
})
@XmlSeeAlso({
    FiguurType.class,
    BouwvlakType.class,
    MaatvoeringType.class,
    GebiedsaanduidingType.class,
    LettertekenaanduidingType.class
})
public abstract class AanduidingType
    extends PlanobjectType
{

    @XmlElement(required = true)
    protected CodeType naam;
    @XmlElement(required = true)
    protected BestemmingsplangebiedPropertyType plangebied;
    protected BestemmingsvlakPropertyType bestemmingsvlak;

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setNaam(CodeType value) {
        this.naam = value;
    }

    /**
     * Gets the value of the plangebied property.
     * 
     * @return
     *     possible object is
     *     {@link BestemmingsplangebiedPropertyType }
     *     
     */
    public BestemmingsplangebiedPropertyType getPlangebied() {
        return plangebied;
    }

    /**
     * Sets the value of the plangebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestemmingsplangebiedPropertyType }
     *     
     */
    public void setPlangebied(BestemmingsplangebiedPropertyType value) {
        this.plangebied = value;
    }

    /**
     * Gets the value of the bestemmingsvlak property.
     * 
     * @return
     *     possible object is
     *     {@link BestemmingsvlakPropertyType }
     *     
     */
    public BestemmingsvlakPropertyType getBestemmingsvlak() {
        return bestemmingsvlak;
    }

    /**
     * Sets the value of the bestemmingsvlak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestemmingsvlakPropertyType }
     *     
     */
    public void setBestemmingsvlak(BestemmingsvlakPropertyType value) {
        this.bestemmingsvlak = value;
    }

}
