//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 04:49:50 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BeleidsbeslissingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BeleidsbeslissingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="concrete beleidsbeslissing"/>
 *     &lt;enumeration value="essentiele beslissing"/>
 *     &lt;enumeration value="indicatieve uitspraak"/>
 *     &lt;enumeration value="toelichting"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BeleidsbeslissingType")
@XmlEnum
public enum BeleidsbeslissingType {

    @XmlEnumValue("concrete beleidsbeslissing")
    CONCRETE_BELEIDSBESLISSING("concrete beleidsbeslissing"),
    @XmlEnumValue("essentiele beslissing")
    ESSENTIELE_BESLISSING("essentiele beslissing"),
    @XmlEnumValue("indicatieve uitspraak")
    INDICATIEVE_UITSPRAAK("indicatieve uitspraak"),
    @XmlEnumValue("toelichting")
    TOELICHTING("toelichting");
    private final String value;

    BeleidsbeslissingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BeleidsbeslissingType fromValue(String v) {
        for (BeleidsbeslissingType c: BeleidsbeslissingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
