//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 02:05:22 PM CEST 
//


package nl.b3p.imro._2006._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for BesluitgebiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BesluitgebiedType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ravi.nl/imro2006}PlanologischGebiedType">
 *       &lt;sequence>
 *         &lt;element name="besluitnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gemeenteCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geometrie" type="{http://www.ravi.nl/imro2006}VlakMultiVlakPropertyType"/>
 *         &lt;element name="locatieNaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="naam" type="{http://www.opengis.net/gml}CodeType"/>
 *         &lt;element name="ontwerper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="overheid" type="{http://www.ravi.nl/imro2006}OverhedenType"/>
 *         &lt;element name="plangebied" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="provincieCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusBeslissing" type="{http://www.ravi.nl/imro2006}PlanstatusBPenDatumPropertyType"/>
 *         &lt;element name="typeBesluitgebied" type="{http://www.ravi.nl/imro2006}BesluittypeType"/>
 *         &lt;element name="verwijzingNaarExternPlan" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="verwijzingNaarTekst" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="verwijzingNorm" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="woonplaatsNaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BesluitgebiedType", propOrder = {
    "besluitnummer",
    "gemeenteCode",
    "geometrie",
    "locatieNaam",
    "naam",
    "ontwerper",
    "overheid",
    "plangebied",
    "provincieCode",
    "statusBeslissing",
    "typeBesluitgebied",
    "verwijzingNaarExternPlan",
    "verwijzingNaarTekst",
    "verwijzingNorm",
    "woonplaatsNaam"
})
public class BesluitgebiedType
    extends PlanologischGebiedType
{

    @XmlElement(required = true)
    protected String besluitnummer;
    protected String gemeenteCode;
    @XmlAnyElement
    protected Element geometrie;
    protected String locatieNaam;
    @XmlElement(required = true)
    protected CodeType naam;
    @XmlElement(required = true)
    protected String ontwerper;
    @XmlElement(required = true)
    protected OverhedenType overheid;
    protected String plangebied;
    protected String provincieCode;
    @XmlElement(required = true)
    protected PlanstatusBPenDatumPropertyType statusBeslissing;
    @XmlElement(required = true)
    protected BesluittypeType typeBesluitgebied;
    protected List<String> verwijzingNaarExternPlan;
    @XmlElement(required = true)
    protected List<String> verwijzingNaarTekst;
    @XmlElement(required = true)
    protected List<String> verwijzingNorm;
    protected String woonplaatsNaam;

    /**
     * Gets the value of the besluitnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBesluitnummer() {
        return besluitnummer;
    }

    /**
     * Sets the value of the besluitnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBesluitnummer(String value) {
        this.besluitnummer = value;
    }

    /**
     * Gets the value of the gemeenteCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGemeenteCode() {
        return gemeenteCode;
    }

    /**
     * Sets the value of the gemeenteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGemeenteCode(String value) {
        this.gemeenteCode = value;
    }

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the locatieNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocatieNaam() {
        return locatieNaam;
    }

    /**
     * Sets the value of the locatieNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocatieNaam(String value) {
        this.locatieNaam = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setNaam(CodeType value) {
        this.naam = value;
    }

    /**
     * Gets the value of the ontwerper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntwerper() {
        return ontwerper;
    }

    /**
     * Sets the value of the ontwerper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntwerper(String value) {
        this.ontwerper = value;
    }

    /**
     * Gets the value of the overheid property.
     * 
     * @return
     *     possible object is
     *     {@link OverhedenType }
     *     
     */
    public OverhedenType getOverheid() {
        return overheid;
    }

    /**
     * Sets the value of the overheid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverhedenType }
     *     
     */
    public void setOverheid(OverhedenType value) {
        this.overheid = value;
    }

    /**
     * Gets the value of the plangebied property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlangebied() {
        return plangebied;
    }

    /**
     * Sets the value of the plangebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlangebied(String value) {
        this.plangebied = value;
    }

    /**
     * Gets the value of the provincieCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincieCode() {
        return provincieCode;
    }

    /**
     * Sets the value of the provincieCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincieCode(String value) {
        this.provincieCode = value;
    }

    /**
     * Gets the value of the statusBeslissing property.
     * 
     * @return
     *     possible object is
     *     {@link PlanstatusBPenDatumPropertyType }
     *     
     */
    public PlanstatusBPenDatumPropertyType getStatusBeslissing() {
        return statusBeslissing;
    }

    /**
     * Sets the value of the statusBeslissing property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanstatusBPenDatumPropertyType }
     *     
     */
    public void setStatusBeslissing(PlanstatusBPenDatumPropertyType value) {
        this.statusBeslissing = value;
    }

    /**
     * Gets the value of the typeBesluitgebied property.
     * 
     * @return
     *     possible object is
     *     {@link BesluittypeType }
     *     
     */
    public BesluittypeType getTypeBesluitgebied() {
        return typeBesluitgebied;
    }

    /**
     * Sets the value of the typeBesluitgebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link BesluittypeType }
     *     
     */
    public void setTypeBesluitgebied(BesluittypeType value) {
        this.typeBesluitgebied = value;
    }

    /**
     * Gets the value of the verwijzingNaarExternPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verwijzingNaarExternPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerwijzingNaarExternPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVerwijzingNaarExternPlan() {
        if (verwijzingNaarExternPlan == null) {
            verwijzingNaarExternPlan = new ArrayList<String>();
        }
        return this.verwijzingNaarExternPlan;
    }

    /**
     * Gets the value of the verwijzingNaarTekst property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verwijzingNaarTekst property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerwijzingNaarTekst().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVerwijzingNaarTekst() {
        if (verwijzingNaarTekst == null) {
            verwijzingNaarTekst = new ArrayList<String>();
        }
        return this.verwijzingNaarTekst;
    }

    /**
     * Gets the value of the verwijzingNorm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verwijzingNorm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerwijzingNorm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVerwijzingNorm() {
        if (verwijzingNorm == null) {
            verwijzingNorm = new ArrayList<String>();
        }
        return this.verwijzingNorm;
    }

    /**
     * Gets the value of the woonplaatsNaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWoonplaatsNaam() {
        return woonplaatsNaam;
    }

    /**
     * Sets the value of the woonplaatsNaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWoonplaatsNaam(String value) {
        this.woonplaatsNaam = value;
    }

}
