//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 10:51:25 AM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LijnMultiLijnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LijnMultiLijnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="geometrieLijn" type="{http://www.opengis.net/gml}CurvePropertyType"/>
 *         &lt;element name="geometrieMultiLijn" type="{http://www.opengis.net/gml}MultiCurvePropertyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LijnMultiLijnType", propOrder = {
    "geometrieLijn",
    "geometrieMultiLijn"
})
public class LijnMultiLijnType {

    protected CurvePropertyType geometrieLijn;
    protected MultiCurvePropertyType geometrieMultiLijn;

    /**
     * Gets the value of the geometrieLijn property.
     * 
     * @return
     *     possible object is
     *     {@link CurvePropertyType }
     *     
     */
    public CurvePropertyType getGeometrieLijn() {
        return geometrieLijn;
    }

    /**
     * Sets the value of the geometrieLijn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurvePropertyType }
     *     
     */
    public void setGeometrieLijn(CurvePropertyType value) {
        this.geometrieLijn = value;
    }

    /**
     * Gets the value of the geometrieMultiLijn property.
     * 
     * @return
     *     possible object is
     *     {@link MultiCurvePropertyType }
     *     
     */
    public MultiCurvePropertyType getGeometrieMultiLijn() {
        return geometrieMultiLijn;
    }

    /**
     * Sets the value of the geometrieMultiLijn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiCurvePropertyType }
     *     
     */
    public void setGeometrieMultiLijn(MultiCurvePropertyType value) {
        this.geometrieMultiLijn = value;
    }

}
