//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 04:49:50 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatrixEnWaardePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatrixEnWaardePropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ravi.nl/imro2006}MatrixEnWaarde"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatrixEnWaardePropertyType", propOrder = {
    "matrixEnWaarde"
})
public class MatrixEnWaardePropertyType {

    @XmlElementRef(name = "MatrixEnWaarde", namespace = "http://www.ravi.nl/imro2006", type = JAXBElement.class)
    protected JAXBElement<? extends MatrixEnWaardeType> matrixEnWaarde;

    /**
     * Gets the value of the matrixEnWaarde property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MatrixEnWaardeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MatrixFiguurType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MatrixSymboolType }{@code >}
     *     
     */
    public JAXBElement<? extends MatrixEnWaardeType> getMatrixEnWaarde() {
        return matrixEnWaarde;
    }

    /**
     * Sets the value of the matrixEnWaarde property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MatrixEnWaardeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MatrixFiguurType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MatrixSymboolType }{@code >}
     *     
     */
    public void setMatrixEnWaarde(JAXBElement<? extends MatrixEnWaardeType> value) {
        this.matrixEnWaarde = value;
    }

}
