//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 10:51:25 AM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanstatusNPType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlanstatusNPType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kabinetsstandpunt"/>
 *     &lt;enumeration value="kabinetsvoornemen"/>
 *     &lt;enumeration value="resultaten van inspraak bestuurlijk overleg en advies"/>
 *     &lt;enumeration value="vastgesteld beleid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlanstatusNPType")
@XmlEnum
public enum PlanstatusNPType {

    @XmlEnumValue("kabinetsstandpunt")
    KABINETSSTANDPUNT("kabinetsstandpunt"),
    @XmlEnumValue("kabinetsvoornemen")
    KABINETSVOORNEMEN("kabinetsvoornemen"),
    @XmlEnumValue("resultaten van inspraak bestuurlijk overleg en advies")
    RESULTATEN_VAN_INSPRAAK_BESTUURLIJK_OVERLEG_EN_ADVIES("resultaten van inspraak bestuurlijk overleg en advies"),
    @XmlEnumValue("vastgesteld beleid")
    VASTGESTELD_BELEID("vastgesteld beleid");
    private final String value;

    PlanstatusNPType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlanstatusNPType fromValue(String v) {
        for (PlanstatusNPType c: PlanstatusNPType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
