//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 02:05:22 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanstatusPPType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlanstatusPPType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Awb bezwaar"/>
 *     &lt;enumeration value="beroep afdeling bestuursrechtspraak"/>
 *     &lt;enumeration value="concept"/>
 *     &lt;enumeration value="goedgekeurd"/>
 *     &lt;enumeration value="goedgekeurd; geheel goedgekeurd"/>
 *     &lt;enumeration value="goedgekeurd; goedgekeurd met uitzondering van onthoudingen"/>
 *     &lt;enumeration value="goedkeuring onthouden"/>
 *     &lt;enumeration value="ontwerp"/>
 *     &lt;enumeration value="uitspraak afdeling bestuursrechtspraak"/>
 *     &lt;enumeration value="uitspraak afdeling bestuursrechtspraak; alsnog goedgekeurd"/>
 *     &lt;enumeration value="uitspraak afdeling bestuursrechtspraak; alsnog goedkeuring onthouden"/>
 *     &lt;enumeration value="vastgesteld"/>
 *     &lt;enumeration value="vastgesteld beleid"/>
 *     &lt;enumeration value="vigerend"/>
 *     &lt;enumeration value="voorlopige voorziening"/>
 *     &lt;enumeration value="voorontwerp"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlanstatusPPType")
@XmlEnum
public enum PlanstatusPPType {

    @XmlEnumValue("Awb bezwaar")
    AWB_BEZWAAR("Awb bezwaar"),
    @XmlEnumValue("beroep afdeling bestuursrechtspraak")
    BEROEP_AFDELING_BESTUURSRECHTSPRAAK("beroep afdeling bestuursrechtspraak"),
    @XmlEnumValue("concept")
    CONCEPT("concept"),
    @XmlEnumValue("goedgekeurd")
    GOEDGEKEURD("goedgekeurd"),
    @XmlEnumValue("goedgekeurd; geheel goedgekeurd")
    GOEDGEKEURD_GEHEEL_GOEDGEKEURD("goedgekeurd; geheel goedgekeurd"),
    @XmlEnumValue("goedgekeurd; goedgekeurd met uitzondering van onthoudingen")
    GOEDGEKEURD_GOEDGEKEURD_MET_UITZONDERING_VAN_ONTHOUDINGEN("goedgekeurd; goedgekeurd met uitzondering van onthoudingen"),
    @XmlEnumValue("goedkeuring onthouden")
    GOEDKEURING_ONTHOUDEN("goedkeuring onthouden"),
    @XmlEnumValue("ontwerp")
    ONTWERP("ontwerp"),
    @XmlEnumValue("uitspraak afdeling bestuursrechtspraak")
    UITSPRAAK_AFDELING_BESTUURSRECHTSPRAAK("uitspraak afdeling bestuursrechtspraak"),
    @XmlEnumValue("uitspraak afdeling bestuursrechtspraak; alsnog goedgekeurd")
    UITSPRAAK_AFDELING_BESTUURSRECHTSPRAAK_ALSNOG_GOEDGEKEURD("uitspraak afdeling bestuursrechtspraak; alsnog goedgekeurd"),
    @XmlEnumValue("uitspraak afdeling bestuursrechtspraak; alsnog goedkeuring onthouden")
    UITSPRAAK_AFDELING_BESTUURSRECHTSPRAAK_ALSNOG_GOEDKEURING_ONTHOUDEN("uitspraak afdeling bestuursrechtspraak; alsnog goedkeuring onthouden"),
    @XmlEnumValue("vastgesteld")
    VASTGESTELD("vastgesteld"),
    @XmlEnumValue("vastgesteld beleid")
    VASTGESTELD_BELEID("vastgesteld beleid"),
    @XmlEnumValue("vigerend")
    VIGEREND("vigerend"),
    @XmlEnumValue("voorlopige voorziening")
    VOORLOPIGE_VOORZIENING("voorlopige voorziening"),
    @XmlEnumValue("voorontwerp")
    VOORONTWERP("voorontwerp");
    private final String value;

    PlanstatusPPType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlanstatusPPType fromValue(String v) {
        for (PlanstatusPPType c: PlanstatusPPType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
