//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 04:49:50 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlangebiedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlangebiedType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ravi.nl/imro2006}PlanologischGebiedType">
 *       &lt;sequence>
 *         &lt;element name="typePlan" type="{http://www.ravi.nl/imro2006}RuimtelijkPlanType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlangebiedType", propOrder = {
    "typePlan"
})
@XmlSeeAlso({
    NationaalPlangebiedType.class,
    StructuurvisieGebiedType.class,
    BestemmingsplangebiedType.class,
    ProvinciaalPlangebiedType.class
})
public abstract class PlangebiedType
    extends PlanologischGebiedType
{

    @XmlElement(required = true)
    protected RuimtelijkPlanType typePlan;

    /**
     * Gets the value of the typePlan property.
     * 
     * @return
     *     possible object is
     *     {@link RuimtelijkPlanType }
     *     
     */
    public RuimtelijkPlanType getTypePlan() {
        return typePlan;
    }

    /**
     * Sets the value of the typePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuimtelijkPlanType }
     *     
     */
    public void setTypePlan(RuimtelijkPlanType value) {
        this.typePlan = value;
    }

}
