//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 02:05:22 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RechtstypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RechtstypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="beheer"/>
 *     &lt;enumeration value="beheer; corporatie"/>
 *     &lt;enumeration value="beheer; overheid"/>
 *     &lt;enumeration value="beheer; particulier"/>
 *     &lt;enumeration value="eigendom"/>
 *     &lt;enumeration value="eigendom; corporatie"/>
 *     &lt;enumeration value="eigendom; overheid"/>
 *     &lt;enumeration value="eigendom; particulier"/>
 *     &lt;enumeration value="gebruik"/>
 *     &lt;enumeration value="gebruik; eigen"/>
 *     &lt;enumeration value="gebruik; verhuur"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RechtstypeType")
@XmlEnum
public enum RechtstypeType {

    @XmlEnumValue("beheer")
    BEHEER("beheer"),
    @XmlEnumValue("beheer; corporatie")
    BEHEER_CORPORATIE("beheer; corporatie"),
    @XmlEnumValue("beheer; overheid")
    BEHEER_OVERHEID("beheer; overheid"),
    @XmlEnumValue("beheer; particulier")
    BEHEER_PARTICULIER("beheer; particulier"),
    @XmlEnumValue("eigendom")
    EIGENDOM("eigendom"),
    @XmlEnumValue("eigendom; corporatie")
    EIGENDOM_CORPORATIE("eigendom; corporatie"),
    @XmlEnumValue("eigendom; overheid")
    EIGENDOM_OVERHEID("eigendom; overheid"),
    @XmlEnumValue("eigendom; particulier")
    EIGENDOM_PARTICULIER("eigendom; particulier"),
    @XmlEnumValue("gebruik")
    GEBRUIK("gebruik"),
    @XmlEnumValue("gebruik; eigen")
    GEBRUIK_EIGEN("gebruik; eigen"),
    @XmlEnumValue("gebruik; verhuur")
    GEBRUIK_VERHUUR("gebruik; verhuur");
    private final String value;

    RechtstypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RechtstypeType fromValue(String v) {
        for (RechtstypeType c: RechtstypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
