//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.31 at 02:05:22 PM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusEnBestuurlijkeDoorwerkingPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusEnBestuurlijkeDoorwerkingPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ravi.nl/imro2006}StatusEnBestuurlijkeDoorwerking"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusEnBestuurlijkeDoorwerkingPropertyType", propOrder = {
    "statusEnBestuurlijkeDoorwerking"
})
public class StatusEnBestuurlijkeDoorwerkingPropertyType {

    @XmlElement(name = "StatusEnBestuurlijkeDoorwerking", required = true)
    protected StatusEnBestuurlijkeDoorwerkingType statusEnBestuurlijkeDoorwerking;

    /**
     * Gets the value of the statusEnBestuurlijkeDoorwerking property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnBestuurlijkeDoorwerkingType }
     *     
     */
    public StatusEnBestuurlijkeDoorwerkingType getStatusEnBestuurlijkeDoorwerking() {
        return statusEnBestuurlijkeDoorwerking;
    }

    /**
     * Sets the value of the statusEnBestuurlijkeDoorwerking property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnBestuurlijkeDoorwerkingType }
     *     
     */
    public void setStatusEnBestuurlijkeDoorwerking(StatusEnBestuurlijkeDoorwerkingType value) {
        this.statusEnBestuurlijkeDoorwerking = value;
    }

}
