//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 10:51:25 AM CEST 
//


package nl.b3p.imro._2006._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for VerbindingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerbindingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ravi.nl/imro2006}PlanobjectType">
 *       &lt;sequence>
 *         &lt;element name="geometrie" type="{http://www.ravi.nl/imro2006}PuntLijnVlakMultiPropertyType" minOccurs="0"/>
 *         &lt;element name="geoNauwkeurigheidInfo" type="{http://www.ravi.nl/imro2006}GeografischeNauwkeurigheidPropertyType" minOccurs="0"/>
 *         &lt;element name="naam" type="{http://www.opengis.net/gml}CodeType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerbindingType", propOrder = {
    "geometrie",
    "geoNauwkeurigheidInfo",
    "naam"
})
@XmlSeeAlso({
    ProvinciaalVerbindingType.class,
    GemeentelijkVerbindingType.class,
    NationaalVerbindingType.class
})
public abstract class VerbindingType
    extends PlanobjectType
{

    @XmlAnyElement
    protected Element geometrie;
    protected GeografischeNauwkeurigheidPropertyType geoNauwkeurigheidInfo;
    @XmlElement(required = true)
    protected CodeType naam;

    /**
     * Gets the value of the geometrie property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getGeometrie() {
        return geometrie;
    }

    /**
     * Sets the value of the geometrie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setGeometrie(Element value) {
        this.geometrie = value;
    }

    /**
     * Gets the value of the geoNauwkeurigheidInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GeografischeNauwkeurigheidPropertyType }
     *     
     */
    public GeografischeNauwkeurigheidPropertyType getGeoNauwkeurigheidInfo() {
        return geoNauwkeurigheidInfo;
    }

    /**
     * Sets the value of the geoNauwkeurigheidInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeografischeNauwkeurigheidPropertyType }
     *     
     */
    public void setGeoNauwkeurigheidInfo(GeografischeNauwkeurigheidPropertyType value) {
        this.geoNauwkeurigheidInfo = value;
    }

    /**
     * Gets the value of the naam property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getNaam() {
        return naam;
    }

    /**
     * Sets the value of the naam property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setNaam(CodeType value) {
        this.naam = value;
    }

}
